
pub struct Field {
    pub off: u32,
    pub name: &'static str,
    pub sig: &'static str,
}

pub struct Mgr {
    pub tag: &'static str,
    pub size: u32,
    pub fields: &'static [Field],
}

pub static SYS: &[(u32, &str, Option<&str>)] = &[
    (0x0004, "VMGetIoManager", Some("VmIoManagerTag")),
    (0x000c, "VMGetLcdManager", Some("VmLcdManagerTag")),
    (0x0014, "VMGetTimeManager", Some("VmTimeManagerTag")),
    (0x001c, "VMGetCtrlManager", Some("VmCtrlManagerTag")),
    (0x0024, "VMGetMemoryManager", Some("VmMemoryManagerTag")),
    (0x002c, "VMGetBillingManager", Some("VmBillingManagerTag")),
    (0x0034, "VMGetScreenManager", Some("VmScreenManagerTag")),
    (0x003c, "VMGetNetManager", Some("VmNetManagerTag")),
    (0x0044, "VMGetUcs2StrManager", Some("VmUcs2StrManagerTag")),
    (0x004c, "VMGetSysManager", Some("VmSysManagerTag")),
    (0x0054, "VMGetDFScriptManager", Some("VmDFScriptManagerTag")),
    (0x005c, "VMGetGameLcdManager", Some("VmGameLcdManagerTag")),
    (0x0064, "VMGetGameUtilManager", Some("VmGameUtilManagerTag")),
    (0x006c, "VMGetDFEnginelManager", Some("VmDFEnginelManagerTag")),
    (0x0074, "VMGetNetAppManager", Some("VmNetAppManagerTag")),
    (0x007c, "VMGetAudioManager", Some("VmAudioManagerTag")),
    (0x0084, "VMGetGameManagerOld", Some("GameManagerOldTag")),
    (0x0090, "vMGetGSensorManager", None),
    (0x0098, "vMGetVmStdManager", Some("VmStdManagerTag")),
    (0x00a0, "vMGetDlLoadManager", Some("VmDlLoadManagerTag")),
    (0x00a4, "vMGetDlRsManager", Some("VmDlResourceManagerTag")),
    (0x00ac, "vMGetDlImageManager", Some("VmDlImageManagerTag")),
    (0x00b8, "vMGetVmImManager", Some("VmImManagerTag")),
    (0x00c8, "VmGetVideoManager", Some("VmVideoManagerTag")),
    (0x00cc, "VmGetDlWPayManager", Some("VmDLWPayManagerTag")),
];

static F_0: &[Field] = &[
    Field { off: 0x0000, name: "IMG_CreateImageFormRes", sig: "" },
    Field { off: 0x0028, name: "IMG_Destory", sig: "" },
    Field { off: 0x002c, name: "GAME_isKeyDown", sig: "" },
    Field { off: 0x0030, name: "GAME_isKeyHold", sig: "" },
    Field { off: 0x005c, name: "GetStreamDataFormRes", sig: "" },
    Field { off: 0x00c8, name: "CdRectPoint", sig: "" },
    Field { off: 0x00e4, name: "Sqrt", sig: "" },
    Field { off: 0x00e8, name: "initMemoryBlock", sig: "" },
    Field { off: 0x00f0, name: "SCREEN_ChangeScreen", sig: "" },
    Field { off: 0x00f4, name: "SCREEN_NotifyLoadResource", sig: "" },
    Field { off: 0x00f8, name: "SCREEN_IsPointerHold", sig: "" },
    Field { off: 0x00fc, name: "SCREEN_IsPointerDown", sig: "" },
    Field { off: 0x0100, name: "SCREEN_IsPointerUp", sig: "" },
    Field { off: 0x0104, name: "SCREEN_IsPointerDrag", sig: "" },
    Field { off: 0x0108, name: "SCREEN_GetPointerX", sig: "" },
    Field { off: 0x010c, name: "SCREEN_GetPointerY", sig: "" },
    Field { off: 0x0110, name: "Get_CurKeyDownState", sig: "" },
    Field { off: 0x0140, name: "initDreamFactoryEngine", sig: "" },
    Field { off: 0x0144, name: "DF_SetDataPackage", sig: "" },
    Field { off: 0x0148, name: "DF_GetDataPackage", sig: "" },
    Field { off: 0x014c, name: "DF_GetResourceByResourceID", sig: "" },
    Field { off: 0x0150, name: "DF_GetResourceByFileName", sig: "" },
    Field { off: 0x0154, name: "DF_GetResourceNameByID", sig: "" },
    Field { off: 0x0158, name: "DF_GetResourceIDByFileName", sig: "" },
    Field { off: 0x015c, name: "DF_GetTResource", sig: "" },
    Field { off: 0x0160, name: "DF_GetStreamTResource", sig: "" },
    Field { off: 0x0164, name: "DF_DataPackage_ShowFileList", sig: "" },
    Field { off: 0x0168, name: "DF_String_Equal", sig: "" },
    Field { off: 0x016c, name: "DF_ReadShort", sig: "" },
    Field { off: 0x0170, name: "DF_ReadInt", sig: "" },
    Field { off: 0x0174, name: "DF_File_ReadShort", sig: "" },
    Field { off: 0x0178, name: "DF_File_ReadInt", sig: "" },
    Field { off: 0x017c, name: "DF_WriteShort", sig: "" },
    Field { off: 0x0180, name: "DF_WriteInt", sig: "" },
    Field { off: 0x0184, name: "DF_ReadString", sig: "" },
    Field { off: 0x0188, name: "DF_ReadStringEx", sig: "" },
    Field { off: 0x018c, name: "DF_File_ReadString", sig: "" },
    Field { off: 0x0190, name: "DF_File_ReadToBuffer", sig: "" },
    Field { off: 0x0194, name: "DF_ReadString2", sig: "" },
    Field { off: 0x0198, name: "DF_GetMemoryBlock", sig: "" },
    Field { off: 0x019c, name: "DF_Sin", sig: "" },
    Field { off: 0x01a0, name: "DF_Cos", sig: "" },
    Field { off: 0x01a4, name: "DF_Degree", sig: "" },
    Field { off: 0x01a8, name: "DF_CollectionTest", sig: "" },
    Field { off: 0x01ac, name: "DF_SwapVal", sig: "" },
    Field { off: 0x01b0, name: "DF_GetFormatString", sig: "" },
    Field { off: 0x01b8, name: "initDFDataPackage", sig: "" },
    Field { off: 0x0214, name: "memcpy", sig: "" },
    Field { off: 0x0218, name: "strlen", sig: "" },
    Field { off: 0x021c, name: "memset", sig: "" },
    Field { off: 0x0220, name: "sprintf", sig: "" },
    Field { off: 0x0224, name: "vm_log_trace", sig: "" },
    Field { off: 0x0228, name: "VmGetRand", sig: "" },
    Field { off: 0x022c, name: "vsprintf", sig: "" },
    Field { off: 0x0230, name: "strncpy", sig: "" },
    Field { off: 0x0234, name: "strcpy", sig: "" },
    Field { off: 0x0238, name: "strcat", sig: "" },
    Field { off: 0x023c, name: "atol", sig: "" },
];
static F_1: &[Field] = &[
    Field { off: 0x0000, name: "vMAudioSetVolume", sig: "void (VMUINT8, VMBOOLEAN)" },
    Field { off: 0x0004, name: "vMAudioPlayByData", sig: "VMINT16 (VMUINT8 *, VMUINT8)" },
    Field { off: 0x0008, name: "vMAudioPlayWithDataPackage", sig: "VMINT16 (gm_u32, VMUINT8, DF_DataPackage *)" },
    Field { off: 0x000c, name: "vMAudioPlayForGame", sig: "VMINT16 (gm_u32, VMUINT8)" },
    Field { off: 0x0010, name: "vMAudioPlayForApp", sig: "VMINT16 (gm_u32, VMUINT8)" },
    Field { off: 0x0014, name: "vMAudioPause", sig: "VMBOOLEAN ()" },
    Field { off: 0x0018, name: "vMAudioResume", sig: "VMBOOLEAN ()" },
    Field { off: 0x001c, name: "vMAudioStop", sig: "VMBOOLEAN ()" },
    Field { off: 0x0020, name: "vMAduioGetState", sig: "VMUINT8 ()" },
    Field { off: 0x0024, name: "VmMp3PlayByStream", sig: "VMBOOLEAN (vm_mp3PlayCallback)" },
    Field { off: 0x0028, name: "VmMp3PauseByStream", sig: "void ()" },
    Field { off: 0x002c, name: "VmMp3ResumeByStream", sig: "void ()" },
    Field { off: 0x0030, name: "VmMp3StopBystream", sig: "void ()" },
    Field { off: 0x0034, name: "VmMp3PlayByFile", sig: "void (VMUINT16 *, vm_mp3PlayCallback)" },
    Field { off: 0x0038, name: "VmMp3PauseByFile", sig: "void ()" },
    Field { off: 0x003c, name: "VmMp3ResumeByFile", sig: "void ()" },
    Field { off: 0x0040, name: "VmMp3StopByFile", sig: "void ()" },
    Field { off: 0x0044, name: "VmMp3GetProgressTime", sig: "void (VMUINT32 *, VMUINT32 *)" },
    Field { off: 0x0048, name: "VmMp3StreamInit", sig: "void (vm_mp3GetByteFromBuffer_CallBack, vm_mp3PeekBuffer_CallBack, vm_mp3setBufferPos_CallBack)" },
    Field { off: 0x004c, name: "VmAMRStartPlayInit", sig: "void (" },
    Field { off: 0x0050, name: "VmAMRStopPlay", sig: "void ()" },
    Field { off: 0x0054, name: "VmAMRplay", sig: "void (VMUINT16 *, VMUINT16)" },
    Field { off: 0x0058, name: "VmAMRStartRecord", sig: "VMBOOLEAN (void *)" },
    Field { off: 0x005c, name: "VmAMRStopRecord", sig: "void ()" },
    Field { off: 0x0060, name: "VmSetAMRRecBS", sig: "void (VMUINT32)" },
    Field { off: 0x0064, name: "VmMp3PlayByFileEx", sig: "void (VmFileDevType, VMUINT16 *, vm_mp3PlayCallback)" },
    Field { off: 0x0068, name: "vMStartAudioRecordEx", sig: "VMBOOLEAN (CB_AMR_DECODER *, CBAudioFormat)" },
    Field { off: 0x006c, name: "vMStopAudioRecordEx", sig: "void ()" },
    Field { off: 0x0070, name: "CB_AUD_StartPlay_InitEx", sig: "void (CB_AMR_DECODER *, CBAudioFormat)" },
    Field { off: 0x0074, name: "CB_AUD_StartPlayEx", sig: "void (VMUINT16 *, VMUINT16, CBAudioFormat)" },
    Field { off: 0x0078, name: "CB_AUD_StopPlayEx", sig: "void ()" },
];
static F_2: &[Field] = &[
    Field { off: 0x0000, name: "BILLING_GetPayNumByAppId", sig: "VMUINT16 (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE)" },
    Field { off: 0x0004, name: "BILLING_GetRemainDay", sig: "VMUINT32 (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE)" },
    Field { off: 0x0008, name: "BILLING_Pay", sig: "void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, Billing_callback_func_t)" },
    Field { off: 0x000c, name: "BILLING_PayMoreTimes", sig: "void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, Billing_callback_func_t, VMUINT16)" },
    Field { off: 0x0010, name: "BILLING_IsRegisterBillingInfo", sig: "VMBOOLEAN (NETAPP_BILLING_APPID_TYPE)" },
    Field { off: 0x0014, name: "BILLING_RegisterBillingInfo", sig: "VMBOOLEAN (NETAPP_BILLING_APPID_TYPE, VMUINT32)" },
    Field { off: 0x0018, name: "BILLING_SetBillingStatus", sig: "VMBOOLEAN (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_STATUS_TYPE)" },
    Field { off: 0x001c, name: "BILLING_GetBillingStatus", sig: "NETAPP_BILLING_STATUS_TYPE (NETAPP_BILLING_APPID_TYPE)" },
    Field { off: 0x0020, name: "BILLING_IsNeedPay", sig: "VMBOOLEAN (NETAPP_BILLING_APPID_TYPE)" },
    Field { off: 0x0024, name: "BILLING_IsInTryStatus", sig: "VMBOOLEAN (NETAPP_BILLING_APPID_TYPE)" },
    Field { off: 0x0028, name: "BIllING_OpenBillingPromptWin", sig: "void (NETAPP_BILLING_APPID_TYPE)" },
    Field { off: 0x002c, name: "BILLING_GetTryDay", sig: "VMUINT16 (NETAPP_BILLING_APPID_TYPE)" },
    Field { off: 0x0030, name: "BILLING_PayForCBB", sig: "void (NETAPP_BILLING_APPID_TYPE, VMUINT16, VMUINT32, Billing_callback_func_t)" },
    Field { off: 0x0034, name: "BILLING_PayForPwd", sig: "void (Billing_callback_func_t)" },
    Field { off: 0x0038, name: "BILLING_GetCdownOption5", sig: "VMUINT8 ()" },
    Field { off: 0x003c, name: "Billing_SendSpecSms", sig: "VMBOOLEAN (VMUINT16, VMUINT8 *, VMUINT8, VMUINT8 *, VMUINT16, VMBOOLEAN, SmSCallback)" },
    Field { off: 0x0040, name: "Billing_CancelSms", sig: "VMBOOLEAN ()" },
    Field { off: 0x0044, name: "CDownIsMonthApp", sig: "VMBOOLEAN (VMUINT16, NETAPP_BILLING_METHOD_TYPE)" },
    Field { off: 0x0048, name: "CDownGetFileNameByAppID", sig: "VMBOOLEAN (VMUINT16, VMUINT8 **, VMUINT8 *, VMUINT16 *)" },
    Field { off: 0x004c, name: "BILLING_GetSmsNum", sig: "VMUINT16 (VMUINT16, VMUINT8)" },
    Field { off: 0x0050, name: "BILLING_NewMonthPay", sig: "VMBOOLEAN (" },
    Field { off: 0x0054, name: "BILLING_NewMonthCancel", sig: "VMBOOLEAN (NewMonthPayInfo *, Billing_callback_func_t)" },
    Field { off: 0x0058, name: "BILLING_CleanAppMonthBillInfo", sig: "VMBOOLEAN (VMUINT16)" },
    Field { off: 0x005c, name: "BILLING_GetValidDayByAppId", sig: "VMUINT16 (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE)" },
    Field { off: 0x0060, name: "BILLING_GetBillSmsAddr", sig: "void (VMUINT16, VMUINT16, VMCHAR *)" },
    Field { off: 0x0064, name: "BILLING_GetBillSmsSuf", sig: "void (VMUINT16, VMUINT16, VMCHAR *)" },
    Field { off: 0x0068, name: "BILLING_Pay2", sig: "void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, Billing_callback_func_t, VMUINT32)" },
    Field { off: 0x006c, name: "BILLING_GetAppUsedStatus", sig: "VMUINT8 (VMUINT16)" },
    Field { off: 0x0070, name: "BILLING_SetAppUsedStatus", sig: "void (VMUINT16, VMUINT8)" },
    Field { off: 0x0074, name: "BILLING_GetPayTipContent", sig: "void (VMUINT16, VMUINT16, VMCHAR *)" },
    Field { off: 0x0078, name: "BILLING_Pay3", sig: "void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, Billing_callback_func_t, VMUINT32, VMBOOLEAN)" },
    Field { off: 0x007c, name: "BILLING_SendRegisterSms", sig: "VMBOOLEAN (VMCHAR *, VMCHAR *, VMBOOLEAN, Billing_callback_func_t)" },
    Field { off: 0x0080, name: "BILLING_CDownOption8", sig: "VMUINT8 ()" },
    Field { off: 0x0084, name: "BILLING_CDownOption9", sig: "VMUINT8 ()" },
    Field { off: 0x0088, name: "BILLING_CDownOption10", sig: "VMUINT8 ()" },
    Field { off: 0x008c, name: "BILLING_Register", sig: "void (SmSCallback)" },
    Field { off: 0x0090, name: "BILLING_PayForCBB3", sig: "void (NETAPP_BILLING_APPID_TYPE, VMUINT16, VMUINT32, Billing_callback_func_t, VMBOOLEAN)" },
    Field { off: 0x0094, name: "BILLING_IsWPay", sig: "VMBOOLEAN ()" },
    Field { off: 0x0098, name: "BILLING_GetPayType", sig: "VMUINT8 (VMUINT16, VMUINT16)" },
    Field { off: 0x009c, name: "BILLING_GetDownLoadFee", sig: "VMUINT8 (VMUINT16)" },
    Field { off: 0x00a0, name: "BILLING_GETUsedFee", sig: "VMUINT8 (VMUINT16)" },
    Field { off: 0x00a4, name: "BILLING_Pay3InMM", sig: "void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, Billing_callback_func_t, VMUINT32, VMBOOLEAN)" },
    Field { off: 0x00a8, name: "BILLING_PayForCBB3InMM", sig: "void (NETAPP_BILLING_APPID_TYPE, VMUINT16, VMUINT32, Billing_callback_func_t, VMBOOLEAN, VMUINT16, VMCHAR *)" },
    Field { off: 0x00ac, name: "BILLING_GetFMMPayTip", sig: "void (NETAPP_BILLING_APPID_TYPE, NETAPP_BILLING_METHOD_TYPE, VMUINT16, VMCHAR *, Billing_callback_func_t)" },
];
static F_3: &[Field] = &[
    Field { off: 0x0000, name: "VmPubDrawSoftkeyBar", sig: "void (VmImageType *, VMSTR, VMSTR, VMSTR)" },
    Field { off: 0x0004, name: "VmPubDrawSoftkeyBarEx", sig: "void (VmImageType *, VMSTR, VMSTR, VMSTR, VMUINT16)" },
    Field { off: 0x0008, name: "VmPubDrawWinTitle", sig: "void (VmImageType *, VMSTR)" },
    Field { off: 0x000c, name: "vmPubDrawWinTitleEx", sig: "void (VmImageType *, VMSTR, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0010, name: "vmPubTpPressSoftkeyBar", sig: "VMBOOLEAN (VmImageType *, VMSTR, VMINT16, VMINT16, VmSoftType)" },
    Field { off: 0x0014, name: "InitCoolbarListBox", sig: "VMBOOLEAN (" },
    Field { off: 0x0018, name: "InitCoolbarListBoxEx", sig: "VMBOOLEAN (CoolbarListBox **, VMUINT16, Rect, VMUINT8, VMBOOLEAN, CoolbarListBox_callback_func_t)" },
    Field { off: 0x001c, name: "CbPopBox_Init", sig: "void (" },
    Field { off: 0x0020, name: "CbPopBox_InitEx", sig: "void (CB_PopBox **" },
    Field { off: 0x0024, name: "VmPubDrawWinTitleWithColor", sig: "void (VmImageType *, VMSTR, VMUINT16)" },
    Field { off: 0x0028, name: "vmInputText", sig: "VMBOOLEAN (CBInputTextCallback, CBInputTextParam *)" },
    Field { off: 0x002c, name: "vmInputPassword", sig: "VMBOOLEAN (CBInputTextCallback, CBInputTextParam *)" },
    Field { off: 0x0030, name: "vmInputClose", sig: "void ()" },
    Field { off: 0x0034, name: "vmInputIsOpen", sig: "VMBOOLEAN ()" },
    Field { off: 0x0038, name: "vmInputDummy", sig: "void (void *)" },
    Field { off: 0x003c, name: "vmPubDrawUcs2SoftkeyBar", sig: "void (VmImageType *, VMWSTR, VMWSTR, VMWSTR)" },
    Field { off: 0x0040, name: "vmPubDrawUcs2SoftkeyBarEx", sig: "void (VmImageType *, VMWSTR, VMWSTR, VMWSTR, VMUINT16)" },
    Field { off: 0x0044, name: "vmPubTpPressUcs2SoftkeyBar", sig: "VMBOOLEAN (VmImageType *, VMWSTR, VMINT16, VMINT16, VmSoftType)" },
    Field { off: 0x0048, name: "vmPubDrawUcs2WinTitle", sig: "void (VmImageType *, VMWSTR)" },
    Field { off: 0x004c, name: "vmPubDrawUcs2WinTitleWithColor", sig: "void (VmImageType *, VMWSTR, VMUINT16)" },
    Field { off: 0x0050, name: "vmPubDrawUcs2WinTitleEx", sig: "void (VmImageType *, VMWSTR, VMUINT16, VMUINT16, VMUINT16)" },
];
static F_4: &[Field] = &[
    Field { off: 0x0000, name: "initDFMap", sig: "void (" },
    Field { off: 0x0004, name: "initDFMapRenderBuffer", sig: "void (" },
    Field { off: 0x0008, name: "initDFMapVScollBuffer", sig: "void (" },
    Field { off: 0x000c, name: "initDFPictureLibrary", sig: "void (DF_PictureLibrary *, int)" },
    Field { off: 0x0010, name: "initDFRecord", sig: "void (" },
    Field { off: 0x0014, name: "initDFScene", sig: "void (" },
    Field { off: 0x0018, name: "initDFSpriteLibrary", sig: "void (" },
    Field { off: 0x001c, name: "initDFWindows", sig: "void (" },
    Field { off: 0x0020, name: "initDreamFactoryEngine", sig: "void ()" },
    Field { off: 0x0024, name: "initDFActor", sig: "void (" },
    Field { off: 0x0028, name: "initDFDataPackage", sig: "void (DF_DataPackage *, gm_s16)" },
    Field { off: 0x002c, name: "GetSceneMapVScollBufferPtr", sig: "DF_MapVScollBuffer *()" },
    Field { off: 0x0030, name: "GetDF_MapRenderBufferPtr", sig: "DF_MapRenderBuffer *()" },
    Field { off: 0x0034, name: "DF_MapRenderBuffer_Windows_Render", sig: "void (void *)" },
    Field { off: 0x0038, name: "DF_SendMessage", sig: "void (DF_Windows *, short, void *)" },
];
static F_5: &[Field] = &[
    Field { off: 0x0000, name: "XS_Init", sig: "Script *()" },
    Field { off: 0x0004, name: "XS_ShutDown", sig: "void ()" },
    Field { off: 0x0008, name: "XS_LoadScript", sig: "int (char *" },
    Field { off: 0x000c, name: "XS_RunScripts", sig: "void (int)" },
    Field { off: 0x0010, name: "XS_ResetScript", sig: "void (int)" },
    Field { off: 0x0014, name: "XS_CallScriptFunc", sig: "void (int, char *)" },
    Field { off: 0x0018, name: "XS_InvokeScriptFunc", sig: "void (int, char *)" },
    Field { off: 0x001c, name: "XS_RegisterHostAPIFunc", sig: "void (int, char *, HostAPIFuncPntr)" },
    Field { off: 0x0020, name: "XS_StartScript", sig: "void (int)" },
    Field { off: 0x0024, name: "XS_StopScript", sig: "void (int)" },
    Field { off: 0x0028, name: "XS_PauseScript", sig: "void (int, int)" },
    Field { off: 0x002c, name: "XS_UnpauseScript", sig: "void (int)" },
    Field { off: 0x0030, name: "XS_GetReturnValueAsInt", sig: "int (int)" },
    Field { off: 0x0034, name: "XS_GetReturnValueAsFloat", sig: "float (int)" },
    Field { off: 0x0038, name: "XS_GetReturnValueAsString", sig: "char *(int)" },
    Field { off: 0x003c, name: "XS_ReturnFromHost", sig: "void (int, int)" },
    Field { off: 0x0040, name: "XS_ReturnIntFromHost", sig: "void (int, int, int)" },
    Field { off: 0x0044, name: "XS_ReturnFloatFromHost", sig: "void (int, int, float)" },
    Field { off: 0x0048, name: "XS_ReturnStringFromHost", sig: "void (int, int, char *)" },
    Field { off: 0x004c, name: "XS_GetParamAsInt", sig: "int (int, int)" },
    Field { off: 0x0050, name: "XS_GetParamAsFloat", sig: "float (int, int)" },
    Field { off: 0x0054, name: "XS_GetParamAsString", sig: "char *(int, int)" },
];
static F_6: &[Field] = &[
    Field { off: 0x0000, name: "vmWPayEnterCharge", sig: "void (VMBOOLEAN, WPayEnterCallBack, VMUINT16, VMUINT32)" },
    Field { off: 0x0004, name: "vmWPayEnterBuy", sig: "void (VMBOOLEAN, VMUINT32, WPayEnterCallBack, VMUINT16" },
    Field { off: 0x0008, name: "vmWPayGetCbMoney", sig: "void (VMBOOLEAN, WPayEnterCallBack)" },
    Field { off: 0x000c, name: "vmWPaySetPayName", sig: "void (VMCHAR *)" },
    Field { off: 0x0010, name: "vmWPaySetPayPassword", sig: "void (VMCHAR *)" },
    Field { off: 0x0014, name: "vmWPaySetPayPhone", sig: "void (VMCHAR *)" },
    Field { off: 0x0018, name: "vmWPaySetPayPhonePassword", sig: "void (VMCHAR *)" },
    Field { off: 0x001c, name: "vmGetIMEI", sig: "void (VMSTR, VMUINT32)" },
    Field { off: 0x0020, name: "vmWPayEnterPay", sig: "void (VMBOOLEAN, void *)" },
];
static F_7: &[Field] = &[
    Field { off: 0x0000, name: "vmAppStoreInstall", sig: "VMBOOLEAN (" },
    Field { off: 0x0004, name: "vmAppStoreInstallEx", sig: "VMBOOLEAN (AppDataType *, AppStoreCallback)" },
    Field { off: 0x0008, name: "vmAppStoreUninstall", sig: "VMBOOLEAN (VMUINT32, AppType_e)" },
    Field { off: 0x000c, name: "vmAppStoreUninstallEx", sig: "VMBOOLEAN (VMUINT32 *, AppType_e, VMUINT16)" },
    Field { off: 0x0010, name: "vmAppStoreGetAppInfo", sig: "VMBOOLEAN (" },
    Field { off: 0x0014, name: "vmAppStoreGetInstalledAppInfos", sig: "void (" },
    Field { off: 0x0018, name: "vmAppStoreReleaseAppInfos", sig: "void (AppInfoType **)" },
    Field { off: 0x001c, name: "vmAppStorePushMsg", sig: "void (VMUINT32, VMCHAR *)" },
    Field { off: 0x0020, name: "vmAppStoreRunJavaAp", sig: "VMBOOLEAN (VMUINT32)" },
    Field { off: 0x0024, name: "vmAppStoreRunJavaApEx", sig: "VMBOOLEAN (VMUINT32, AppStoreCallback)" },
    Field { off: 0x0028, name: "vmAppStoreRunCbeAp", sig: "VMBOOLEAN (VMUINT32)" },
    Field { off: 0x002c, name: "vmAppStoreSupportJava", sig: "VMBOOLEAN ()" },
    Field { off: 0x0030, name: "vmAppStoreGetPath", sig: "VMUINT16 *()" },
    Field { off: 0x0034, name: "vmGetPhoneType", sig: "PhoneType_e ()" },
    Field { off: 0x0038, name: "vmGetAppNumByType", sig: "VMBOOLEAN (AppType_e, VMUINT16 *)" },
    Field { off: 0x003c, name: "vmGetPhoneSupportApType", sig: "VMUINT32 ()" },
    Field { off: 0x0040, name: "vmAppGetHasLocalIcon", sig: "VMBOOLEAN (VMUINT32, AppType_e)" },
    Field { off: 0x0044, name: "vmAppRunApByIdAndName", sig: "VMBOOLEAN (VMUINT32, AppType_e, VMUINT16 *, AppStoreCallback, ApStartSource)" },
    Field { off: 0x0048, name: "vmAppAddShortCutMenu", sig: "VMBOOLEAN (AppDataType *, VMUINT16)" },
    Field { off: 0x004c, name: "vmAppDelShortCutMenu", sig: "VMBOOLEAN (AppDataType *, VMUINT16)" },
    Field { off: 0x0050, name: "vmAppDownLoadAppFile", sig: "VMBOOLEAN (VMUINT16 *, char *, VMUINT32, DownLoadStateCallBackType)" },
    Field { off: 0x0054, name: "vmGetAppDownUrl", sig: "void (char *, VMUINT8, VMUINT32, VMUINT8, VMUINT8, VMCHAR *)" },
    Field { off: 0x0058, name: "vmAppPreLoadCbeByNameAndId", sig: "VMUINT8 (VMUINT32, VMUINT16 *)" },
    Field { off: 0x005c, name: "vmParseDownloadAppFile", sig: "VMBOOLEAN (VMUINT16 *, AppDataType *)" },
    Field { off: 0x0060, name: "vmApsStopDownloadFile", sig: "VMBOOLEAN ()" },
    Field { off: 0x0064, name: "vmAppQueryStcExist", sig: "VMBOOLEAN (AppInfoType *)" },
    Field { off: 0x0068, name: "vmPreCheckInstallAppPlace", sig: "SpaceStatus ()" },
    Field { off: 0x006c, name: "vmGetInstallFileSystem", sig: "VmFileDevType ()" },
    Field { off: 0x0070, name: "vmSetInstallFileSystem", sig: "void (VmFileDevType)" },
    Field { off: 0x0074, name: "vmSetRunAppFileSystem", sig: "void (VmFileDevType)" },
    Field { off: 0x0078, name: "vmGetRunAppFileSystem", sig: "VmFileDevType ()" },
    Field { off: 0x007c, name: "vmAutoSelectAppDownPlace", sig: "VMBOOLEAN ()" },
    Field { off: 0x0080, name: "vmGetApsVerNum", sig: "VMUINT8 ()" },
    Field { off: 0x0084, name: "vmReadAppStoreCbeVersion", sig: "VMBOOLEAN (void *, VMUINT16)" },
    Field { off: 0x0088, name: "vmWriteAppStoreCbeVersion", sig: "VMBOOLEAN (const void *, VMUINT16)" },
    Field { off: 0x008c, name: "vmGetSecurityCode", sig: "VMBOOLEAN (VMSTR, VMUINT16)" },
    Field { off: 0x0090, name: "vmGetSecurityCodeEx", sig: "VMBOOLEAN (VMSTR, VMUINT16)" },
    Field { off: 0x0094, name: "vmSetAppStoreName", sig: "void (VMWSTR)" },
    Field { off: 0x0098, name: "vmGetAppStoreName", sig: "VMWSTR ()" },
];
static F_8: &[Field] = &[
    Field { off: 0x0000, name: "vMDrawStandardImage", sig: "void (VMUINT32, VMINT32, VMINT32, VMINT32, VMINT32, VMUINT8 *, VMUINT32, VMUINT8)" },
    Field { off: 0x0004, name: "vMGetStandardImageDimension", sig: "void (VMUINT8 *, VMUINT32, VMUINT8, VMINT32 *, VMINT32 *)" },
    Field { off: 0x0008, name: "vMGetStandardImageType", sig: "void (VMUINT8 *, VMUINT8 *)" },
    Field { off: 0x000c, name: "vMDrawStandardImageEx", sig: "void (VmImageType *, VMUINT32, VMINT32, VMINT32, VMINT32, VMINT32, VMUINT8 *, VMUINT32, VMUINT8)" },
    Field { off: 0x0010, name: "vMImageDecoderAllocMemory", sig: "void (VMUINT32, void **)" },
    Field { off: 0x0014, name: "vMImageDecoderFreeMemory", sig: "void (void **)" },
    Field { off: 0x0018, name: "vMImageDecoderGetImageData", sig: "VMUINT8 *(GddiImage *)" },
    Field { off: 0x001c, name: "vMImageDecoderRegImageCodecHandler", sig: "void (GddiImageFormat" },
    Field { off: 0x0020, name: "decodePngStartExt", sig: "VmImageType *(gm_u8 *, VmImageType *, gm_bool)" },
    Field { off: 0x0024, name: "pngcrc32", sig: "unsigned int (unsigned int" },
    Field { off: 0x0028, name: "pnginflate", sig: "int (void *, int)" },
    Field { off: 0x002c, name: "pnginflateInit", sig: "int (void *)" },
    Field { off: 0x0030, name: "pnginflateEnd", sig: "int (void *)" },
    Field { off: 0x0034, name: "pnginflateReset", sig: "int (void *)" },
];
static F_9: &[Field] = &[
    Field { off: 0x0000, name: "vlDlSetCurrContextAddress", sig: "void (VMUINT32 **, VMBOOLEAN)" },
    Field { off: 0x0004, name: "vlDlSetContextAddress", sig: "void (VMUINT16, VMUINT32 **, VMBOOLEAN)" },
    Field { off: 0x0008, name: "vlDlUnLoadCurrApp", sig: "void (VMBOOLEAN)" },
    Field { off: 0x000c, name: "vlDlUnLoadApp", sig: "void (VMUINT16, VMBOOLEAN)" },
    Field { off: 0x0010, name: "vmDlParseAndCopy", sig: "VMINT8 (const VMUINT16 *, VMUINT16 *, VMUINT8 *, VMUINT32 *)" },
    Field { off: 0x0014, name: "vlDlLoadApp", sig: "VMBOOLEAN (VMUINT16)" },
    Field { off: 0x0018, name: "vlDlLoadAppEx", sig: "VMBOOLEAN (VMUINT16, VMUINT8)" },
    Field { off: 0x001c, name: "vlDlAppIsInDl", sig: "VMBOOLEAN (VMUINT16)" },
    Field { off: 0x0020, name: "vmGetcurrInnerAppId", sig: "VMUINT16 ()" },
    Field { off: 0x0024, name: "CBInnerInit_qqIn", sig: "void (VMUINT8 *, VMUINT32, VMUINT32, VMUINT8 *, VMUINT8 *, VMUINT32, VMUINT32, VMUINT8 *)" },
    Field { off: 0x0028, name: "VmGetCBEInfoByFileName", sig: "VMBOOLEAN (VMUINT16 *, VMUINT32 *, VMUINT32 *, VMUINT16 *, VMUINT16 *)" },
];
static F_10: &[Field] = &[
    Field { off: 0x0000, name: "vmGetDataPackage", sig: "DF_DataPackage *(VMBOOLEAN)" },
    Field { off: 0x0004, name: "vmResGetTxtWithDataPackage", sig: "VMCHAR *(VMUINT32, DF_DataPackage *)" },
    Field { off: 0x0008, name: "vmResGetDefTxt", sig: "VMCHAR *(VMUINT32)" },
    Field { off: 0x000c, name: "vmResGetTxtForGame", sig: "VMCHAR *(VMUINT32)" },
    Field { off: 0x0010, name: "IMG_InitDataPage", sig: "void (tResource, gm_s16)" },
    Field { off: 0x0014, name: "IMG_InitInnerDataPageEx", sig: "void (tResource)" },
    Field { off: 0x0018, name: "IMG_InitDataPageEx", sig: "void (tResource, gm_s16, DF_DataPackage *)" },
    Field { off: 0x001c, name: "IMG_InitDataPageTxt", sig: "void (gm_u32)" },
    Field { off: 0x0020, name: "IMG_ReleaseDataPage", sig: "void ()" },
    Field { off: 0x0024, name: "IMG_CreateImageFormIdEx", sig: "VmImageType *(gm_u32, DF_DataPackage *, VmImageType *)" },
    Field { off: 0x0028, name: "IMG_CreateImageFormStream", sig: "VmImageType *(gm_u8 *, VmImageType *)" },
    Field { off: 0x002c, name: "IMG_CreateImageFormName", sig: "VmImageType *(char *, DF_DataPackage *, VmImageType *)" },
    Field { off: 0x0030, name: "vMDestoryImage", sig: "VMBOOLEAN (VmImageType *)" },
    Field { off: 0x0034, name: "vMCreateImage", sig: "VMBOOLEAN (VMUINT16, VmImageType *)" },
    Field { off: 0x0038, name: "vMSetCurrDataPackage", sig: "void (DF_DataPackage *)" },
    Field { off: 0x003c, name: "vMGetCurrDataPackage", sig: "DF_DataPackage *()" },
    Field { off: 0x0040, name: "vmFreeDataBuffer", sig: "void ()" },
    Field { off: 0x0044, name: "DF_DataPackage_GetFileOffset", sig: "gm_u32 ()" },
    Field { off: 0x0048, name: "DF_DataPackage_GetFullPaths", sig: "gm_u16 *()" },
    Field { off: 0x004c, name: "DF_DataPackage_GetFileLens", sig: "gm_u32 ()" },
];
static F_11: &[Field] = &[
    Field { off: 0x0000, name: "vmGsensorInit", sig: "void ()" },
    Field { off: 0x0004, name: "vmGsensorStop", sig: "void ()" },
    Field { off: 0x0008, name: "vmGsensorStartTile", sig: "void (VmGSensorBack)" },
    Field { off: 0x000c, name: "vmGsensorStartShake", sig: "void (VmGSensorBack)" },
    Field { off: 0x0010, name: "vmGsensorStartTurn", sig: "void (VmGSensorBack)" },
    Field { off: 0x0014, name: "vmGsensorStartSwing", sig: "void (VmGSensorBack)" },
    Field { off: 0x0018, name: "vmGsensorPowerOff", sig: "void ()" },
    Field { off: 0x001c, name: "vmGSenserIsSupportInCb", sig: "VMBOOLEAN ()" },
    Field { off: 0x0020, name: "vmGsensorGetDevInfo", sig: "VMBOOLEAN (" },
    Field { off: 0x0024, name: "vmGsensorRegistMotionChange", sig: "VMBOOLEAN (VMUINT32, VMBOOLEAN, GsensorMotionListenrCb, VMBOOLEAN, void *)" },
    Field { off: 0x0028, name: "vmGsensorRegistNotifyChange", sig: "VMBOOLEAN (GSENSOR_NOTIFY_PROFILE, VMBOOLEAN, GsensorNotifyCb, VMBOOLEAN, void *)" },
    Field { off: 0x002c, name: "vmGsensorGetLastMotionInfo", sig: "VMBOOLEAN (VMUINT32, VMUINT32 *)" },
];
static F_12: &[Field] = &[
    Field { off: 0x0000, name: "CreateImage", sig: "VmImageType *(tResource)" },
    Field { off: 0x0004, name: "DrawImageWithClip", sig: "void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16)" },
    Field { off: 0x0008, name: "DrawImageClipAndAlpha", sig: "void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16)" },
    Field { off: 0x000c, name: "DrawFullScreen", sig: "void (VmImageType *)" },
    Field { off: 0x0010, name: "DrawNumber", sig: "void (VmImageType *, gm_s32, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_u8)" },
    Field { off: 0x0014, name: "DrawUI", sig: "void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16)" },
    Field { off: 0x0018, name: "DrawUIFourXRepeat", sig: "void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16)" },
    Field { off: 0x001c, name: "DrawUISingleRepeat", sig: "void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16)" },
    Field { off: 0x0020, name: "DrawUIHorizontal", sig: "void (VmImageType *, gm_s16, gm_s16, gm_s16)" },
    Field { off: 0x0024, name: "DrawString", sig: "void (char *, gm_s16, gm_s16, gm_s16, gm_u32)" },
    Field { off: 0x0028, name: "DrawStringEx", sig: "void (VmImageType *, char *, gm_s16, gm_s16, gm_s16, gm_u32)" },
    Field { off: 0x002c, name: "ReleaseImage", sig: "void (VmImageType *)" },
    Field { off: 0x0030, name: "SetClip", sig: "void (gm_s16, gm_s16, gm_s16, gm_s16)" },
    Field { off: 0x0034, name: "IMG_GetHeight", sig: "gm_u16 (VmImageType *)" },
    Field { off: 0x0038, name: "IMG_GetWidth", sig: "gm_u16 (VmImageType *)" },
    Field { off: 0x003c, name: "ToRGB", sig: "gm_u16 (" },
    Field { off: 0x0040, name: "DrawLine", sig: "void (" },
    Field { off: 0x0044, name: "DrawLineEx", sig: "void (VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_u16)" },
    Field { off: 0x0048, name: "DrawRect", sig: "void (VmGraphics *, gm_s16, gm_s16, gm_s16, gm_s16, gm_u16)" },
    Field { off: 0x004c, name: "FillRect", sig: "void (VmGraphics *, gm_s16, gm_s16, gm_u16, gm_u16, gm_u16)" },
    Field { off: 0x0050, name: "GetStreamDataFormRes", sig: "gm_u8 *(tResource)" },
    Field { off: 0x0054, name: "GetClip", sig: "GAME_RECT_T ()" },
    Field { off: 0x0058, name: "CheckClip", sig: "void (gm_s16, gm_s16)" },
    Field { off: 0x005c, name: "GetFontWidth", sig: "int ()" },
    Field { off: 0x0060, name: "GetFontWidth_char", sig: "int ()" },
    Field { off: 0x0064, name: "GetFontHeight", sig: "int ()" },
    Field { off: 0x0068, name: "GetFontHeight_char", sig: "int ()" },
    Field { off: 0x006c, name: "DrawImageWithClipEx", sig: "void (VmImageType *, VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16)" },
    Field { off: 0x0070, name: "DrawImageClipAndAlphaEx", sig: "void (VmImageType *, VmImageType *, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16)" },
    Field { off: 0x0074, name: "DrawImageNumberEx", sig: "void (VmImageType *, VmImageType *, gm_s32, gm_s16, gm_s16, gm_s16, gm_s16, gm_s16, gm_u8)" },
    Field { off: 0x0078, name: "RefresScreen", sig: "void ()" },
    Field { off: 0x007c, name: "NumToZhiFei", sig: "gm_u8 *(gm_u8)" },
    Field { off: 0x0080, name: "GetLCDBuffer", sig: "gm_u16 *()" },
    Field { off: 0x0084, name: "InitTextBox", sig: "void (" },
    Field { off: 0x0088, name: "getTextLine", sig: "gm_s32 (char *, gm_s32)" },
    Field { off: 0x008c, name: "InitSprite", sig: "void (" },
    Field { off: 0x0090, name: "initListener", sig: "void (" },
    Field { off: 0x0094, name: "releaseListener", sig: "void (Listener *)" },
    Field { off: 0x0098, name: "talkRepaintListener", sig: "void (Listener *, gm_s16, gm_s16, gm_s16, gm_s16)" },
    Field { off: 0x009c, name: "initTalker", sig: "void (" },
];
static F_13: &[Field] = &[
    Field { off: 0x0000, name: "CdRect", sig: "gm_bool (int, int, int, int, int, int, int, int)" },
    Field { off: 0x0004, name: "CdRectPoint", sig: "gm_bool (int, int, int, int, int, int)" },
    Field { off: 0x0008, name: "CdRect2", sig: "gm_bool (int, int, int, int, int, int, int, int)" },
    Field { off: 0x000c, name: "CdRectPoint2", sig: "gm_bool (int, int, int, int, int, int)" },
    Field { off: 0x0010, name: "Abs", sig: "gm_s16 (gm_s16)" },
    Field { off: 0x0014, name: "Max", sig: "gm_s16 (gm_s16, gm_s16)" },
    Field { off: 0x0018, name: "Min", sig: "gm_s16 (gm_s16, gm_s16)" },
    Field { off: 0x001c, name: "Random", sig: "gm_s16 (gm_s16, gm_s16)" },
    Field { off: 0x0020, name: "Sqrt", sig: "gm_s32 (gm_s32)" },
    Field { off: 0x0024, name: "DF_SetDataPackage", sig: "void (DF_DataPackage *)" },
    Field { off: 0x0028, name: "DF_GetDataPackage", sig: "DF_DataPackage *()" },
    Field { off: 0x002c, name: "DF_GetResourceByResourceID", sig: "char *(int)" },
    Field { off: 0x0030, name: "DF_GetResourceByFileName", sig: "char *(char *)" },
    Field { off: 0x0034, name: "DF_GetResourceNameByID", sig: "char *(int)" },
    Field { off: 0x0038, name: "DF_GetResourceIDByFileName", sig: "int (char *)" },
    Field { off: 0x003c, name: "DF_GetTResource", sig: "tResource (char *)" },
    Field { off: 0x0040, name: "DF_GetStreamTResource", sig: "tResource (char *)" },
    Field { off: 0x0044, name: "DF_DataPackage_ShowFileList", sig: "void ()" },
    Field { off: 0x0048, name: "DF_String_Equal", sig: "gm_bool (char *, char *)" },
    Field { off: 0x004c, name: "ReadShort", sig: "gm_s16 (char *" },
    Field { off: 0x0050, name: "DF_ReadInt", sig: "gm_s32 (char *, gm_s32 *)" },
    Field { off: 0x0054, name: "DF_File_ReadShort", sig: "gm_s16 (VMFILE)" },
    Field { off: 0x0058, name: "DF_File_ReadInt", sig: "gm_s32 (VMFILE)" },
    Field { off: 0x005c, name: "DF_WriteShort", sig: "void (char *, gm_s32 *" },
    Field { off: 0x0060, name: "DF_WriteInt", sig: "void (char *, gm_s32 *, gm_s32)" },
    Field { off: 0x0064, name: "DF_ReadString", sig: "char *(char *, gm_s32 *)" },
    Field { off: 0x0068, name: "DF_ReadStringEx", sig: "void (" },
    Field { off: 0x006c, name: "DF_File_ReadString", sig: "char *(VMFILE)" },
    Field { off: 0x0070, name: "DF_File_ReadToBuffer", sig: "void (VMFILE, char *, gm_s32)" },
    Field { off: 0x0074, name: "DF_ReadString2", sig: "char *(char *, gm_s32 *)" },
    Field { off: 0x0078, name: "DF_GetMemoryBlock", sig: "MemoryBlock *()" },
    Field { off: 0x007c, name: "DF_Sin", sig: "gm_s32 (gm_s32)" },
    Field { off: 0x0080, name: "DF_Cos", sig: "gm_s32 (gm_s32)" },
    Field { off: 0x0084, name: "DF_Degree", sig: "gm_s32 (gm_s32, gm_s32)" },
    Field { off: 0x0088, name: "DF_CollectionTest", sig: "gm_bool (Rect, Rect)" },
    Field { off: 0x008c, name: "DF_SwapVal", sig: "void (" },
    Field { off: 0x0090, name: "formatString", sig: "char *(const void *, ...)" },
    Field { off: 0x0094, name: "Storage_Date", sig: "gm_bool (char *, gm_u8 *, int, gm_bool, gm_bool)" },
    Field { off: 0x0098, name: "Game_stricmp", sig: "gm_u32 (char *, char *)" },
    Field { off: 0x009c, name: "Game_strnicmp", sig: "gm_u32 (char *, char *, int)" },
];
static F_14: &[Field] = &[
    Field { off: 0x0000, name: "reserver_func01", sig: "void (void *)" },
    Field { off: 0x0004, name: "reserver_func02", sig: "void (void *)" },
    Field { off: 0x0008, name: "reserver_func03", sig: "void (void *)" },
    Field { off: 0x000c, name: "reserver_func04", sig: "void (void *)" },
    Field { off: 0x0010, name: "reserver_func05", sig: "void (void *)" },
    Field { off: 0x0014, name: "reserver_func06", sig: "void (void *)" },
    Field { off: 0x0018, name: "reserver_func07", sig: "void (void *)" },
    Field { off: 0x001c, name: "reserver_func08", sig: "void (void *)" },
];
static F_15: &[Field] = &[
    Field { off: 0x0000, name: "Vm_file_open", sig: "VMFILE (VmFileDevType" },
    Field { off: 0x0004, name: "Vm_file_close", sig: "void (VMFILE)" },
    Field { off: 0x0008, name: "Vm_file_exist", sig: "VMBOOLEAN (VmFileDevType, const VMUINT16 *)" },
    Field { off: 0x000c, name: "Vm_file_direxist", sig: "VMBOOLEAN (VmFileDevType, const VMUINT16 *)" },
    Field { off: 0x0010, name: "Vm_file_read", sig: "VMUINT32 (" },
    Field { off: 0x0014, name: "Vm_file_write", sig: "VMUINT32 (void *, VMUINT32, VMFILE)" },
    Field { off: 0x0018, name: "Vm_file_seek", sig: "VMINT32 (VMFILE, VMINT32, VMINT32)" },
    Field { off: 0x001c, name: "Vm_file_tell", sig: "VMINT32 (VMFILE)" },
    Field { off: 0x0020, name: "Vm_file_getfilesize", sig: "VMINT32 (VMFILE)" },
    Field { off: 0x0024, name: "Vm_file_delete", sig: "VMINT32 (VmFileDevType, const VMUINT16 *)" },
    Field { off: 0x0028, name: "Vm_file_rename", sig: "VMINT32 (VmFileDevType, const VMUINT16 *, const VMUINT16 *)" },
    Field { off: 0x002c, name: "Vm_file_mkdir", sig: "VMINT32 (VmFileDevType, const VMUINT16 *)" },
    Field { off: 0x0030, name: "Vm_file_rmdir", sig: "VMINT32 (VmFileDevType, const VMUINT16 *)" },
    Field { off: 0x0034, name: "Vm_find_first", sig: "VMINT32 (VmFileDevType, const VMUINT16 *, const VMUINT16 *" },
    Field { off: 0x0038, name: "Vm_find_next", sig: "VMINT32 (VmFileDevType, VMINT32, const VMUINT16 *, VMUINT16 *)" },
    Field { off: 0x003c, name: "Vm_find_close", sig: "void (VMINT32)" },
    Field { off: 0x0040, name: "Vm_get_freespace", sig: "VMUINT32 ()" },
    Field { off: 0x0044, name: "Vm_get_sdcardStatus", sig: "VMBOOLEAN ()" },
    Field { off: 0x0048, name: "Vm_GetFilenameFromPath", sig: "void (VMUINT16 *, VMBOOLEAN, VMUINT16, VMUINT16 *)" },
    Field { off: 0x004c, name: "Vm_file_getMp3Dir", sig: "VMUINT16 *()" },
    Field { off: 0x0050, name: "Vm_file_getMp4Dir", sig: "VMUINT16 *()" },
    Field { off: 0x0054, name: "Vm_file_getPicDir", sig: "VMUINT16 *()" },
    Field { off: 0x0058, name: "Vm_file_getBookDir", sig: "VMUINT16 *()" },
    Field { off: 0x005c, name: "Vm_file_truncate", sig: "VMINT32 (VMINT32)" },
    Field { off: 0x0060, name: "vm_file_RdWt", sig: "VMBOOLEAN (" },
    Field { off: 0x0064, name: "Vm_file_getSysDir", sig: "VMUINT16 *()" },
    Field { off: 0x0068, name: "Vm_fmgr_select_entry", sig: "void (" },
    Field { off: 0x006c, name: "Vm_get_freespace_ex", sig: "VMUINT32 (VmFileDevType)" },
    Field { off: 0x0070, name: "Vm_get_sdcardStatusEx", sig: "VMBOOLEAN ()" },
    Field { off: 0x0074, name: "Vm_get_fullname", sig: "void (VmFileDevType, const VMUINT16 *, VMUINT16 *)" },
];
static F_16: &[Field] = &[
    Field { off: 0x0000, name: "VMGetCurrMainScreenImage", sig: "VmImageType *()" },
    Field { off: 0x0004, name: "VMGetLCDBuffer", sig: "VMUINT16 *()" },
    Field { off: 0x0008, name: "VM_InvalidateLcd", sig: "void ()" },
    Field { off: 0x000c, name: "VMGetCurrFontType", sig: "VmFontType ()" },
    Field { off: 0x0010, name: "VMSetCurrFontType", sig: "void (VmFontType)" },
    Field { off: 0x0014, name: "VMGetFontWidth", sig: "VMUINT16 (VMBOOLEAN)" },
    Field { off: 0x0018, name: "VMGetFontHeight", sig: "VMUINT16 (VMBOOLEAN)" },
    Field { off: 0x001c, name: "VMGetStringWidth", sig: "VMUINT16 (VMSTR)" },
    Field { off: 0x0020, name: "VMGetStringHeight", sig: "VMUINT16 (VMSTR)" },
    Field { off: 0x0024, name: "VMDrawString", sig: "void (VMSTR, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0028, name: "VMDrawStringEx", sig: "void (VmImageType *, VMSTR, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x002c, name: "VMDrawStringClipAlign", sig: "VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VmAlignType, VMUINT16)" },
    Field { off: 0x0030, name: "VMDrawStringClip", sig: "VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0034, name: "VMDrawStringRect", sig: "VMUINT32 (VMSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0038, name: "VMDrawLineEx", sig: "VMBOOLEAN (VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x003c, name: "VMDrawLine", sig: "VMBOOLEAN (VmPointType, VmPointType, VMUINT16)" },
    Field { off: 0x0040, name: "VMDrawRect", sig: "VMBOOLEAN (VmRectType, VMUINT16)" },
    Field { off: 0x0044, name: "VMDrawRectEx", sig: "VMBOOLEAN (VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0048, name: "VMFillRect", sig: "VMBOOLEAN (VmRectType, VMUINT16)" },
    Field { off: 0x004c, name: "VMFillRectEx", sig: "VMBOOLEAN (VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0050, name: "vMFillRectWithImage", sig: "VMBOOLEAN (VMUINT16, VMUINT16, VMUINT16, VMUINT16, VmImageType *)" },
    Field { off: 0x0054, name: "vMFillRectWithImageEx", sig: "VMBOOLEAN (VmImageType *, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VmImageType *)" },
    Field { off: 0x0058, name: "VMCreateImage", sig: "VMBOOLEAN (VMUINT16, VmImageType *)" },
    Field { off: 0x005c, name: "VMCreateImageFromInRes", sig: "VMBOOLEAN (VMUINT16, VmImageType *)" },
    Field { off: 0x0060, name: "VMDrawImageWithClipEx", sig: "void (VmImageType *, VmImageType *, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16)" },
    Field { off: 0x0064, name: "VMDrawImageClipAndAlphaEx", sig: "void (VmImageType *, VmImageType *, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16)" },
    Field { off: 0x0068, name: "VMDrawImage", sig: "VMBOOLEAN (VmImageType *, VmPointType)" },
    Field { off: 0x006c, name: "VMDrawImageEx", sig: "VMBOOLEAN (VmImageType *, VMUINT16, VMUINT16)" },
    Field { off: 0x0070, name: "VMDrawImageWithAlpha", sig: "VMBOOLEAN (VmImageType *, VmPointType)" },
    Field { off: 0x0074, name: "VMDrawImageWithClip", sig: "VMBOOLEAN (VmImageType *, VmPointType, VmRectType)" },
    Field { off: 0x0078, name: "VMDrawImageWithClip2", sig: "VMBOOLEAN (VmImageType *, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16)" },
    Field { off: 0x007c, name: "VMDrawImageClipAndAlpha", sig: "VMBOOLEAN (VmImageType *, VmPointType, VmRectType)" },
    Field { off: 0x0080, name: "VMDrawImageClipAndAlpha2", sig: "VMBOOLEAN (VmImageType *, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16, VMINT16)" },
    Field { off: 0x0084, name: "VMGetImageWidth", sig: "VMUINT16 (VmImageType *)" },
    Field { off: 0x0088, name: "VMGetImageHeight", sig: "VMUINT16 (VmImageType *)" },
    Field { off: 0x008c, name: "VMDestoryImage", sig: "VMBOOLEAN (VmImageType *)" },
    Field { off: 0x0090, name: "VMIsBacklightOn", sig: "VMBOOLEAN ()" },
    Field { off: 0x0094, name: "VMCtrlBacklight", sig: "void (VMBOOLEAN)" },
    Field { off: 0x0098, name: "VMGB2UCS2", sig: "VMUINT16 (VMSTR, VMWSTR, VMUINT16)" },
    Field { off: 0x009c, name: "VMUCS2GB", sig: "VMUINT16 (VMWSTR, VMSTR, VMUINT16)" },
    Field { off: 0x00a0, name: "VMWinPointIsInRect", sig: "VMBOOLEAN (VmPointType, VmRectType)" },
    Field { off: 0x00a4, name: "vmResGetTxtWithDataPackage", sig: "VMCHAR *(VMUINT32" },
    Field { off: 0x00a8, name: "VmResGetDefTxt", sig: "VMCHAR *(VMUINT32)" },
    Field { off: 0x00ac, name: "vmResGetTxtForGame", sig: "VMCHAR *(VMUINT32)" },
    Field { off: 0x00b0, name: "IMG_InitDataPage", sig: "void (tResource, gm_s16)" },
    Field { off: 0x00b4, name: "IMG_InitInnerDataPageEx", sig: "void (tResource)" },
    Field { off: 0x00b8, name: "IMG_ReleaseDataPage", sig: "void ()" },
    Field { off: 0x00bc, name: "IMG_InitDataPageEx", sig: "void (tResource, gm_s16, DF_DataPackage *)" },
    Field { off: 0x00c0, name: "IMG_CreateImageFormIdEx", sig: "VmImageType *(gm_u32, DF_DataPackage *, VmImageType *)" },
    Field { off: 0x00c4, name: "IMG_CreateImageFormStream", sig: "VmImageType *(" },
    Field { off: 0x00c8, name: "VMDrawStandardImage", sig: "void (VMUINT32, VMINT32, VMINT32, VMINT32, VMINT32" },
    Field { off: 0x00cc, name: "VMGetStandardImageDimension", sig: "void (VMUINT8 *, VMUINT32, VMUINT8" },
    Field { off: 0x00d0, name: "VMGetStandardImageType", sig: "void (VMUINT8 *, VMUINT8 *)" },
    Field { off: 0x00d4, name: "VMDrawStandardImageEx", sig: "void (VmImageType *, VMUINT32, VMINT32, VMINT32, VMINT32, VMINT32, VMUINT8 *, VMUINT32, VMUINT8)" },
    Field { off: 0x00d8, name: "vMDrawStringBorder", sig: "void (VMSTR, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x00dc, name: "vMDrawStringClipAlignBorder", sig: "VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VmAlignType, VMUINT16)" },
    Field { off: 0x00e0, name: "vMDrawStringClipBorder", sig: "VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x00e4, name: "IMG_InitDataPageTxt", sig: "void (gm_u32)" },
    Field { off: 0x00e8, name: "vMImageDecoderAllocMemory", sig: "void (VMUINT32" },
    Field { off: 0x00ec, name: "vMImageDecoderFreeMemory", sig: "void (void **)" },
    Field { off: 0x00f0, name: "vMImageDecoderGetImageData", sig: "VMUINT8 *(" },
    Field { off: 0x00f4, name: "vMImageDecoderRegImageCodecHandler", sig: "void (GddiImageFormat" },
    Field { off: 0x00f8, name: "VMGetCharWidth", sig: "VMUINT16 (VMUINT16)" },
    Field { off: 0x00fc, name: "vMDrawUcs2String", sig: "void (VMUWSTR, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0100, name: "vMDrawUcs2StringBorder", sig: "void (VMUWSTR, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0104, name: "vMDrawUcs2StringEx", sig: "void (VmImageType *, VMUWSTR, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0108, name: "vMDrawUcs2StringClipAlignBorder", sig: "VMBOOLEAN (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VmAlignType, VMUINT16)" },
    Field { off: 0x010c, name: "vMDrawUcs2StringClipAlign", sig: "VMBOOLEAN (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VmAlignType, VMUINT16)" },
    Field { off: 0x0110, name: "vMDrawUcs2StringClipBorder", sig: "VMBOOLEAN (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0114, name: "vMDrawUcs2StringClip", sig: "VMBOOLEAN (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0118, name: "vMDrawUcs2StringRect", sig: "VMUINT32 (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x011c, name: "vMGetUcs2StringWidth", sig: "VMUINT16 (VMUWSTR)" },
    Field { off: 0x0120, name: "vMGetUcs2StringHeight", sig: "VMUINT16 (VMUWSTR)" },
    Field { off: 0x0124, name: "VmAllowBackLight", sig: "void (VMBOOLEAN)" },
    Field { off: 0x0128, name: "VmGetIsNeedRefreshLcd", sig: "VMBOOLEAN ()" },
    Field { off: 0x012c, name: "VmSetIsNeedRefreshLcd", sig: "void (VMBOOLEAN)" },
    Field { off: 0x0130, name: "VmLCDInvalidateRectEnable", sig: "void (VMBOOLEAN)" },
    Field { off: 0x0134, name: "VmSetVideoIsNeedClosed", sig: "void (VMBOOLEAN)" },
    Field { off: 0x0138, name: "VmGetVideoIsNeedClosed", sig: "VMBOOLEAN ()" },
    Field { off: 0x013c, name: "vMDrawUcs2StringRectEx", sig: "void (VMUWSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16)" },
    Field { off: 0x0140, name: "vMSetCbeFontDataPtr", sig: "void (" },
    Field { off: 0x0144, name: "vMGetFontHeightEx", sig: "VMUINT16 (VMBOOLEAN, VmFontType)" },
    Field { off: 0x0148, name: "vMGetFontWidthEx", sig: "VMUINT16 (VMBOOLEAN, VmFontType)" },
    Field { off: 0x014c, name: "vMGetStringHeightEx", sig: "VMUINT16 (VMSTR, VmFontType)" },
    Field { off: 0x0150, name: "vMGetStringWidthEx", sig: "VMUINT16 (VMSTR, VmFontType)" },
    Field { off: 0x0154, name: "vMShowStringEx", sig: "void (VmImageType *, VMSTR, VMUINT16, VMUINT16, VMUINT16, VmFontType)" },
    Field { off: 0x0158, name: "vMShowString", sig: "void (VMSTR, VMUINT16, VMUINT16, VMUINT16, VmFontType)" },
    Field { off: 0x015c, name: "vMShowStringClipAlign", sig: "VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VmAlignType, VMUINT16, VmFontType)" },
    Field { off: 0x0160, name: "vMShowStringClip", sig: "VMBOOLEAN (VMSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VmFontType)" },
    Field { off: 0x0164, name: "vMShowStringRect", sig: "VMUINT32 (VMSTR, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VMUINT16, VmFontType)" },
    Field { off: 0x0168, name: "vM_InvalidateLcdEx", sig: "void (VMINT32, VMINT32, VMINT32, VMINT32)" },
    Field { off: 0x016c, name: "vMSetFontSize", sig: "void (VMUINT32)" },
    Field { off: 0x0170, name: "vMResetFontSize", sig: "void ()" },
    Field { off: 0x0174, name: "vMUTF82UCS2", sig: "VMUINT16 (VMSTR, VMWSTR)" },
    Field { off: 0x0178, name: "vMUCS2UTF8", sig: "VMUINT16 (VMWSTR, VMSTR)" },
];
static F_17: &[Field] = &[
    Field { off: 0x0000, name: "VMInitIoManager", sig: "void (" },
    Field { off: 0x0004, name: "VMGetIoManager", sig: "VmIoManager *()" },
    Field { off: 0x0008, name: "VMInitLcdManager", sig: "void (" },
    Field { off: 0x000c, name: "VMGetLcdManager", sig: "VmLcdManager *()" },
    Field { off: 0x0010, name: "VMInitTimeManager", sig: "void (" },
    Field { off: 0x0014, name: "VMGetTimeManager", sig: "VmTimeManager *()" },
    Field { off: 0x0018, name: "VMInitCtrlManager", sig: "void (" },
    Field { off: 0x001c, name: "VMGetCtrlManager", sig: "VmCtrlManager *()" },
    Field { off: 0x0020, name: "VMInitMemoryManager", sig: "void (" },
    Field { off: 0x0024, name: "VMGetMemoryManager", sig: "VmMemoryManager *()" },
    Field { off: 0x0028, name: "VMInitBillingManager", sig: "void (" },
    Field { off: 0x002c, name: "VMGetBillingManager", sig: "VmBillingManager *()" },
    Field { off: 0x0030, name: "VMInitScreenManager", sig: "void (" },
    Field { off: 0x0034, name: "VMGetScreenManager", sig: "VmScreenManager *()" },
    Field { off: 0x0038, name: "VMInitNetManager", sig: "void (" },
    Field { off: 0x003c, name: "VMGetNetManager", sig: "VmNetManager *()" },
    Field { off: 0x0040, name: "VMInitUcs2StrManager", sig: "void (" },
    Field { off: 0x0044, name: "VMGetUcs2StrManager", sig: "VmUcs2StrManager *()" },
    Field { off: 0x0048, name: "VMInitSysManager", sig: "void (" },
    Field { off: 0x004c, name: "VMGetSysManager", sig: "VmSysManager *()" },
    Field { off: 0x0050, name: "VMInitDFScriptManager", sig: "void (" },
    Field { off: 0x0054, name: "VMGetDFScriptManager", sig: "VmDFScriptManager *()" },
    Field { off: 0x0058, name: "VMInitGameLcdManager", sig: "void (" },
    Field { off: 0x005c, name: "VMGetGameLcdManager", sig: "VmGameLcdManager *()" },
    Field { off: 0x0060, name: "VMInitGameUtilManager", sig: "void (" },
    Field { off: 0x0064, name: "VMGetGameUtilManager", sig: "VmGameUtilManager *()" },
    Field { off: 0x0068, name: "VMInitDFEnginelManager", sig: "void (" },
    Field { off: 0x006c, name: "VMGetDFEnginelManager", sig: "VmDFEnginelManager *()" },
    Field { off: 0x0070, name: "VMInitNetAppManager", sig: "void (" },
    Field { off: 0x0074, name: "VMGetNetAppManager", sig: "VmNetAppManager *()" },
    Field { off: 0x0078, name: "VMInitAudioManager", sig: "void (" },
    Field { off: 0x007c, name: "VMGetAudioManager", sig: "VmAudioManager *()" },
    Field { off: 0x0080, name: "VMInitGameManagerOld", sig: "void (void *)" },
    Field { off: 0x0084, name: "VMGetGameManagerOld", sig: "void *()" },
    Field { off: 0x0088, name: "VMInitManager", sig: "void (" },
    Field { off: 0x008c, name: "vMInitGSensorManager", sig: "void (" },
    Field { off: 0x0090, name: "vMGetGSensorManager", sig: "VmGSensorManager *()" },
    Field { off: 0x0094, name: "vMInitVmStdManager", sig: "void (" },
    Field { off: 0x0098, name: "vMGetVmStdManager", sig: "VmStdManager *()" },
    Field { off: 0x009c, name: "vMInitDlLoadManager", sig: "void (" },
    Field { off: 0x00a0, name: "vMGetDlLoadManager", sig: "VmDlLoadManager *()" },
    Field { off: 0x00a4, name: "vMGetDlRsManager", sig: "VmDlResourceManager *()" },
    Field { off: 0x00a8, name: "vMInitDlRsManager", sig: "void (VmDlResourceManager *)" },
    Field { off: 0x00ac, name: "vMGetDlImageManager", sig: "VmDlImageManager *()" },
    Field { off: 0x00b0, name: "vMInitDlImageManager", sig: "void (VmDlImageManager *)" },
    Field { off: 0x00b4, name: "vMInitVmImManager", sig: "void (" },
    Field { off: 0x00b8, name: "vMGetVmImManager", sig: "VmImManager *()" },
    Field { off: 0x00bc, name: "vMInitTencentQQManager", sig: "void (" },
    Field { off: 0x00c0, name: "vMInitQQIdleManager", sig: "void (void *)" },
    Field { off: 0x00c4, name: "VmInitVideoManager", sig: "void (" },
    Field { off: 0x00c8, name: "VmGetVideoManager", sig: "VmVideoManager *()" },
    Field { off: 0x00cc, name: "VmGetDlWPayManager", sig: "VmDLWPayManager *()" },
    Field { off: 0x00d0, name: "vMInitEmailIdleManager", sig: "void (void *)" },
];
static F_18: &[Field] = &[
    Field { off: 0x0000, name: "dF_InitMemory", sig: "void (gm_u32)" },
    Field { off: 0x0004, name: "dF_ReleaseMemory", sig: "void ()" },
    Field { off: 0x0008, name: "dF_Malloc_In", sig: "VMBOOLEAN (void **, gm_u32)" },
    Field { off: 0x000c, name: "dF_Free", sig: "void (void **)" },
    Field { off: 0x0010, name: "dF_Memory_gc", sig: "void ()" },
    Field { off: 0x0014, name: "mF_InitMemoryBlock", sig: "void (" },
    Field { off: 0x0018, name: "mF_MemoryBlock_Malloc", sig: "void *(MemoryBlock *, gm_s32)" },
    Field { off: 0x001c, name: "mF_MemoryBlock_Reset", sig: "void (MemoryBlock *)" },
    Field { off: 0x0020, name: "mF_GetGMemoryBlockPtr", sig: "MemoryBlock *()" },
    Field { off: 0x0024, name: "mF_InitGmemoryBlock", sig: "void (gm_s32)" },
    Field { off: 0x0028, name: "mF_ReleaseGmemoryBlock", sig: "void ()" },
    Field { off: 0x002c, name: "mF_resetGmemoryBlock", sig: "void ()" },
    Field { off: 0x0030, name: "mF_MallocGmemoryBlock", sig: "void *(gm_s32)" },
    Field { off: 0x0034, name: "mallocBigMen", sig: "void *(int)" },
    Field { off: 0x0038, name: "freeBigMen", sig: "void (void *)" },
    Field { off: 0x003c, name: "DF_Memory_AttachPointer", sig: "void (void **, void **)" },
    Field { off: 0x0040, name: "mF_MemoryBlock_Release", sig: "void (MemoryBlock *)" },
    Field { off: 0x0044, name: "dF_InitMemoryEx", sig: "void (gm_u32)" },
    Field { off: 0x0048, name: "RemallocBigMen", sig: "void *(void *, int)" },
    Field { off: 0x004c, name: "dF_Malloc_debug", sig: "VMBOOLEAN (void **, gm_u32, const char *, int)" },
    Field { off: 0x0050, name: "mallocBigMen_debug", sig: "void *(VMUINT32, const char *, int)" },
    Field { off: 0x0054, name: "getShareMemAlloced", sig: "VMUINT32 ()" },
    Field { off: 0x0058, name: "mallocBigMen2", sig: "void *(int)" },
    Field { off: 0x005c, name: "freeBigMen2", sig: "void (void *)" },
    Field { off: 0x0060, name: "GetBlockMemInfo", sig: "void (VMUINT32 *" },
    Field { off: 0x0064, name: "mallocSysMem", sig: "void *(VMUINT32)" },
    Field { off: 0x0068, name: "freeSysMen", sig: "void (void *)" },
];
static F_19: &[Field] = &[
    Field { off: 0x0000, name: "coolbar_NetEntry", sig: "void (" },
    Field { off: 0x0004, name: "coolbar_GHEntry", sig: "void (" },
    Field { off: 0x0008, name: "net_SetCommonHandle", sig: "void (NetCommonHandleF)" },
    Field { off: 0x000c, name: "net_set_appPackage_dataSegment", sig: "void (const char *, const char *, VMUINT8 *, VMUINT16 *)" },
    Field { off: 0x0010, name: "net_set_appPackage_dataSegmentExt", sig: "void (const char *, VMUINT32, VMUINT8 *, VMUINT16 *)" },
    Field { off: 0x0014, name: "net_set_appPackage_dataSegment_combi", sig: "void (const char *, const char *, VMUINT8 *, VMUINT16, VMUINT16 *)" },
    Field { off: 0x0018, name: "net_Game_Send_AppPackage", sig: "VMBOOLEAN (VMUINT8 *, VMUINT16, VMUINT8, VMUINT8)" },
    Field { off: 0x001c, name: "net_Game_Send_gamePackage", sig: "VMBOOLEAN (VMUINT8 *, VMUINT16)" },
    Field { off: 0x0020, name: "net_Game_get_userId", sig: "VMUINT32 ()" },
    Field { off: 0x0024, name: "net_Game_set_userId", sig: "void (VMUINT32)" },
    Field { off: 0x0028, name: "net_Game_set_sessionId", sig: "void (VMUINT8 *, VMUINT8)" },
    Field { off: 0x002c, name: "net_Game_get_gameId", sig: "VMUINT32 ()" },
    Field { off: 0x0030, name: "net_Game_set_gameId", sig: "void (VMUINT32)" },
    Field { off: 0x0034, name: "net_Game_get_gameType", sig: "VMUINT8 ()" },
    Field { off: 0x0038, name: "net_Game_set_gameType", sig: "void (VMUINT8)" },
    Field { off: 0x003c, name: "net_Game_get_gamePackageType", sig: "VMUINT8 ()" },
    Field { off: 0x0040, name: "net_Game_set_gamePackageType", sig: "void (VMUINT8)" },
    Field { off: 0x0044, name: "net_Game_get_gameStep", sig: "VMUINT8 ()" },
    Field { off: 0x0048, name: "net_Game_set_gameStep", sig: "void (VMUINT8)" },
    Field { off: 0x004c, name: "net_get_connectId", sig: "VMINT32 ()" },
    Field { off: 0x0050, name: "net_set_connectId", sig: "void (VMINT32)" },
    Field { off: 0x0054, name: "net_Game_Init", sig: "void (VMUINT8, VMUINT8)" },
    Field { off: 0x0058, name: "net_Game_Exit", sig: "void (VMUINT8)" },
    Field { off: 0x005c, name: "net_Game_ready", sig: "void (VMUINT8)" },
    Field { off: 0x0060, name: "net_Game_sitDown", sig: "void (VMUINT8, VMUINT8, VMUINT16)" },
    Field { off: 0x0064, name: "net_Game_send_select_score", sig: "void (VMUINT8, VMUINT8)" },
    Field { off: 0x0068, name: "net_Game_pass", sig: "void (VMUINT8)" },
    Field { off: 0x006c, name: "net_Game_combine_card", sig: "void (VMUINT8 *, VMUINT8, VMUINT8)" },
    Field { off: 0x0070, name: "net_Game_parse_card_value", sig: "void (VMUINT8" },
    Field { off: 0x0074, name: "net_Game_combine_card_value", sig: "void (CCard, VMUINT8 *)" },
    Field { off: 0x0078, name: "net_Game_get_cards", sig: "void (GAME_CARDS, VMUINT8 *, VMUINT8 *, VMUINT8 *, VMUINT8)" },
    Field { off: 0x007c, name: "net_close_channel", sig: "void (VMINT32)" },
    Field { off: 0x0080, name: "net_Game_set_curRmIndex", sig: "void (VMUINT16)" },
    Field { off: 0x0084, name: "net_Game_get_curRmIndex", sig: "VMUINT16 ()" },
    Field { off: 0x0088, name: "net_Game_set_curSerIndex", sig: "void (VMUINT16)" },
    Field { off: 0x008c, name: "net_Game_get_curSerIndex", sig: "VMUINT16 ()" },
    Field { off: 0x0090, name: "net_game_request_personalBasicInfo", sig: "void (VMUINT32)" },
    Field { off: 0x0094, name: "net_game_request_personalGameInfo", sig: "void (VMUINT32, VMUINT8)" },
    Field { off: 0x0098, name: "net_game_request_personalBGInfo", sig: "void (VMUINT32, VMUINT8)" },
    Field { off: 0x009c, name: "net_get_DefaultLoginInfo", sig: "void (LOGIN_INFO_T *)" },
    Field { off: 0x00a0, name: "net_write_DefaultLoginInfo", sig: "void (LOGIN_INFO_T *)" },
    Field { off: 0x00a4, name: "net_Recv_Data", sig: "void (VMUINT8 *, VMUINT32, VMUINT32, NetRequestResultType)" },
    Field { off: 0x00a8, name: "net_build_sessionId", sig: "void (VMINT32)" },
    Field { off: 0x00ac, name: "net_Login", sig: "void (" },
    Field { off: 0x00b0, name: "net_commonRegister", sig: "VMBOOLEAN (VMCHAR *, VMINT32, VMCHAR *, VMCHAR *)" },
    Field { off: 0x00b4, name: "net_OneKeyRegister", sig: "VMBOOLEAN (VMCHAR *, VMINT32)" },
    Field { off: 0x00b8, name: "net_set_UserInfo", sig: "void (" },
    Field { off: 0x00bc, name: "net_get_UserInfo", sig: "USER_BASIC_INFO *()" },
    Field { off: 0x00c0, name: "net_parse_Int8_by_name", sig: "VMBOOLEAN (VMUINT8 *, VMUINT16, const char *, VMUINT8 *)" },
    Field { off: 0x00c4, name: "net_parse_Int16_by_name", sig: "VMBOOLEAN (VMUINT8 *, VMUINT16, const char *, VMUINT16 *)" },
    Field { off: 0x00c8, name: "net_parse_Int32_by_name", sig: "VMBOOLEAN (VMUINT8 *, VMUINT16, const char *, VMUINT32 *)" },
    Field { off: 0x00cc, name: "net_parse_Str_by_name", sig: "VMUINT8 (VMUINT8 *, VMUINT16, const char *, VMUINT8 *, VMUINT16 *)" },
    Field { off: 0x00d0, name: "net_set_serverVer", sig: "void (VMUINT16)" },
    Field { off: 0x00d4, name: "net_get_serverVer", sig: "VMUINT16 ()" },
    Field { off: 0x00d8, name: "net_parse_signedInt32_by_name", sig: "VMBOOLEAN (VMUINT8 *, VMUINT16, const char *, VMINT32 *)" },
    Field { off: 0x00dc, name: "net_get_valueData_offset_by_name", sig: "VMUINT8 (VMUINT8 *, VMUINT16, const char *, VMUINT32 *, VMUINT16 *)" },
    Field { off: 0x00e0, name: "net_set_redirectURL", sig: "void (char *, VMUINT16)" },
    Field { off: 0x00e4, name: "net_get_redirectURL", sig: "char *()" },
    Field { off: 0x00e8, name: "net_Game_Send_AppPackage_NewConnect", sig: "VMBOOLEAN (VMUINT32, VMUINT8 *, VMUINT16, VMUINT8, VMUINT8)" },
    Field { off: 0x00ec, name: "net_Recv_Data_NewConnect", sig: "void (VMUINT8 *, VMUINT32, VMUINT32, NetRequestResultType, VMUINT32)" },
    Field { off: 0x00f0, name: "net_GetAppInfo", sig: "void (VMUINT16 *, VMUINT16 *, VMUINT8 *)" },
];
static F_20: &[Field] = &[
    Field { off: 0x0000, name: "OpenChannel", sig: "VMBOOLEAN (char *, NetRequestMethodType, NetCallBackType, VMUINT32 *)" },
    Field { off: 0x0004, name: "SendData", sig: "VMBOOLEAN (VMUINT32, VMUINT32, VMUINT8 *)" },
    Field { off: 0x0008, name: "CloseChannel", sig: "VMBOOLEAN (VMUINT32)" },
    Field { off: 0x000c, name: "GetHttpData", sig: "VMBOOLEAN (char *, NetCallBackType, VMUINT32 *)" },
    Field { off: 0x0010, name: "PostHttpData", sig: "VMBOOLEAN (char *, VMUINT32, VMUINT8 *, NetCallBackType, VMUINT32 *)" },
    Field { off: 0x0014, name: "CancelHttpConnect", sig: "VMBOOLEAN (VMINT32)" },
    Field { off: 0x0018, name: "OpenChannel2", sig: "VMBOOLEAN (char *, NetRequestMethodType, NetCallBackType2, VMUINT32 *)" },
    Field { off: 0x001c, name: "OpenQQChannel", sig: "VMBOOLEAN (char *, NetRequestMethodType, NetCallBackType, VMUINT32 *)" },
    Field { off: 0x0020, name: "VMGetLinkSetNum", sig: "VMUINT8 ()" },
    Field { off: 0x0024, name: "VMGetLinkSetNameByIndex", sig: "VMUINT16 (VMUINT8, char *, VMUINT8)" },
    Field { off: 0x0028, name: "VMGetWapIndex", sig: "VMUINT8 ()" },
    Field { off: 0x002c, name: "VMGetNetIndex", sig: "VMUINT8 ()" },
    Field { off: 0x0030, name: "SetWapIndex", sig: "void (VMUINT8)" },
    Field { off: 0x0034, name: "SetNetIndex", sig: "void (VMUINT8)" },
    Field { off: 0x0038, name: "GetGateWayByIndex", sig: "VMUINT8 *(VMUINT8)" },
    Field { off: 0x003c, name: "GetPortByIndex", sig: "VMUINT16 (VMUINT8)" },
    Field { off: 0x0040, name: "GetApnByIndex", sig: "VMUINT8 *(VMUINT8)" },
    Field { off: 0x0044, name: "GetHttpDataEx", sig: "VMBOOLEAN (char *, NetCallBackType, VMUINT32 *, VMCHAR *, VMCHAR *, VMBOOLEAN, HTTP_PAGE_GETTYPE)" },
    Field { off: 0x0048, name: "OpenChannelEx", sig: "VMBOOLEAN (char *, NetRequestMethodType, NetCallBackType, VMUINT32 *, VMCHAR *, VMBOOLEAN)" },
    Field { off: 0x004c, name: "PostHttpDataEx", sig: "VMBOOLEAN (char *, VMUINT32, VMUINT8 *, NetCallBackType, VMUINT32 *, VMCHAR *, VMCHAR *, VMBOOLEAN, HTTP_PAGE_GETTYPE)" },
    Field { off: 0x0050, name: "GetGprsStatus", sig: "VM_GPRS_STATE_E ()" },
    Field { off: 0x0054, name: "SetGprsStatus", sig: "void (VM_GPRS_STATE_E)" },
    Field { off: 0x0058, name: "GetCurApn", sig: "void (VMCHAR *)" },
    Field { off: 0x005c, name: "GetDeactiveFlag", sig: "VMUINT8 ()" },
    Field { off: 0x0060, name: "SetDeactiveFlag", sig: "void (VMUINT8)" },
    Field { off: 0x0064, name: "SetStartPos", sig: "VMUINT32 (VMUINT32)" },
    Field { off: 0x0068, name: "GetUAAgent", sig: "void (VMCHAR *)" },
    Field { off: 0x006c, name: "GetWapProfile", sig: "void (VMCHAR *)" },
    Field { off: 0x0070, name: "GetLastNetError", sig: "VMUINT16 ()" },
    Field { off: 0x0074, name: "GetHttpMassData", sig: "VMBOOLEAN (char *, NetCallBackType, VMUINT32 *" },
    Field { off: 0x0078, name: "PostHttpMassData", sig: "VMBOOLEAN (char *, VMUINT32, VMUINT8 *, NetCallBackType, VMUINT32 *, MassDataSendingPara *)" },
    Field { off: 0x007c, name: "VMIsWifiReady", sig: "VMBOOLEAN ()" },
    Field { off: 0x0080, name: "VMGetGPRSCounter", sig: "void (" },
    Field { off: 0x0084, name: "VmSetSockQueryTime", sig: "void (VMUINT32)" },
    Field { off: 0x0088, name: "VmResetSockQueryTime", sig: "void ()" },
    Field { off: 0x008c, name: "VmNetDataReset", sig: "void ()" },
    Field { off: 0x0090, name: "VmGetNetData", sig: "void (VMUINT32 *, VMUINT32 *)" },
    Field { off: 0x0094, name: "VmGetFlowMassage", sig: "void (" },
    Field { off: 0x0098, name: "VmClearFlowMassage", sig: "VMBOOLEAN (VMUINT16)" },
    Field { off: 0x009c, name: "VmDeleteFlowMassage", sig: "VMBOOLEAN (VMUINT16)" },
    Field { off: 0x00a0, name: "VmGetSingleFlowmsg", sig: "VMBOOLEAN (VMUINT16, FlowMsg **)" },
    Field { off: 0x00a4, name: "VmClearAllFlowMassage", sig: "void ()" },
    Field { off: 0x00a8, name: "VmDeleteAllFlowMassage", sig: "void ()" },
];
static F_21: &[Field] = &[
    Field { off: 0x0000, name: "vmSCREEN_ChangeScreen", sig: "void (" },
    Field { off: 0x0004, name: "vmSCREEN_NotifyLoadResource", sig: "void (tScreen *)" },
    Field { off: 0x0008, name: "vmChangeScreen", sig: "void (" },
    Field { off: 0x000c, name: "vmChangeScreenEx", sig: "void (VmScreen *, void *, VMBOOLEAN)" },
    Field { off: 0x0010, name: "vmAddScreen", sig: "void (VmScreen *)" },
    Field { off: 0x0014, name: "vmAddScreenEx", sig: "void (VmScreen *, void *, VMBOOLEAN)" },
    Field { off: 0x0018, name: "vmDeleteScreen", sig: "void (VmScreen *)" },
    Field { off: 0x001c, name: "vmScreenLoadResource", sig: "void (VmScreen *)" },
    Field { off: 0x0020, name: "vmScreenLoadResourceEx", sig: "void (VmScreen *, void *)" },
    Field { off: 0x0024, name: "vmIsScreenFocus", sig: "VMBOOLEAN (VmScreen *)" },
    Field { off: 0x0028, name: "vmIsBottomScreen", sig: "VMBOOLEAN (VmScreen *)" },
    Field { off: 0x002c, name: "vmScreenLogic", sig: "void (VMUINT32, void *)" },
];
static F_22: &[Field] = &[
    Field { off: 0x0000, name: "memcpy", sig: "void *(void *, const void *, unsigned int)" },
    Field { off: 0x0004, name: "strlen", sig: "unsigned int (const char *)" },
    Field { off: 0x0008, name: "memset", sig: "void *(void *, int, unsigned int)" },
    Field { off: 0x000c, name: "sprintf", sig: "int (char *, const char *, ...)" },
    Field { off: 0x0010, name: "printf", sig: "void (char *, ...)" },
    Field { off: 0x0014, name: "rand", sig: "int ()" },
    Field { off: 0x0018, name: "vsprintf", sig: "int (char *, const char *" },
    Field { off: 0x001c, name: "strncpy", sig: "char *(char *, const char *, unsigned int)" },
    Field { off: 0x0020, name: "strcpy", sig: "char *(char *, const char *)" },
    Field { off: 0x0024, name: "strcat", sig: "char *(char *, const char *)" },
    Field { off: 0x0028, name: "atol", sig: "long (const char *)" },
    Field { off: 0x002c, name: "memmove", sig: "void *(void *, const void *, unsigned int)" },
    Field { off: 0x0030, name: "atoi", sig: "int (const char *)" },
    Field { off: 0x0034, name: "pow", sig: "float (float, float)" },
    Field { off: 0x0038, name: "strcmp", sig: "int (const char *, const char *)" },
    Field { off: 0x003c, name: "memcmp", sig: "int (const void *, const void *, size_t)" },
    Field { off: 0x0040, name: "strncmp", sig: "int (const char *, const char *, size_t)" },
    Field { off: 0x0044, name: "setjmp", sig: "int (int *)" },
    Field { off: 0x0048, name: "longjmp", sig: "void (int *, int)" },
    Field { off: 0x004c, name: "atof", sig: "double (const char *)" },
    Field { off: 0x0050, name: "vMstricmp", sig: "VMUINT32 (char *, char *)" },
    Field { off: 0x0054, name: "vMstrnicmp", sig: "VMUINT32 (char *, char *, int)" },
];
static F_23: &[Field] = &[
    Field { off: 0x0000, name: "VMIsSimReady", sig: "VMBOOLEAN ()" },
    Field { off: 0x0004, name: "VmSysIsHaveNetWork", sig: "VMBOOLEAN ()" },
    Field { off: 0x0008, name: "VMIsSystemReady", sig: "VMBOOLEAN ()" },
    Field { off: 0x000c, name: "VMGetOperator", sig: "VmOperatorType ()" },
    Field { off: 0x0010, name: "VMGetIMEI", sig: "void (VMSTR, VMUINT32)" },
    Field { off: 0x0014, name: "VMGetIMSI", sig: "void (VMSTR, VMUINT32)" },
    Field { off: 0x0018, name: "VMGetPrjName", sig: "void (VMSTR, VMUINT32)" },
    Field { off: 0x001c, name: "VMGetPrjVersion", sig: "void (VMSTR, VMUINT32)" },
    Field { off: 0x0020, name: "VMIsCallConnect", sig: "VMBOOLEAN ()" },
    Field { off: 0x0024, name: "VMIsDCopen", sig: "VMBOOLEAN ()" },
    Field { off: 0x0028, name: "VMGetStkCardStatus", sig: "VMBOOLEAN ()" },
    Field { off: 0x002c, name: "VMGetActiveSim", sig: "VMUINT16 ()" },
    Field { off: 0x0030, name: "VmGetCoolbarlistInit", sig: "VMUINT8 ()" },
    Field { off: 0x0034, name: "VmSetFPS", sig: "void (VMUINT32)" },
    Field { off: 0x0038, name: "VmEnterWinClose", sig: "void ()" },
    Field { off: 0x003c, name: "vMAudioIsSupportInCb", sig: "VMBOOLEAN ()" },
    Field { off: 0x0040, name: "vMAssert", sig: "void (char *, VMUINT32)" },
    Field { off: 0x0044, name: "GetCoolbarDirPath", sig: "VMUINT16 (VMUINT16 *)" },
    Field { off: 0x0048, name: "GetVerByAppID", sig: "VMUINT16 (VMUINT16)" },
    Field { off: 0x004c, name: "GetCoolBarFullPath", sig: "void (VMUINT16 *, const char *)" },
    Field { off: 0x0050, name: "vMGSenserIsSupportInCb", sig: "VMBOOLEAN ()" },
    Field { off: 0x0054, name: "VmSendMsg", sig: "VMBOOLEAN (VMUINT16, VMUINT32, void *)" },
    Field { off: 0x0058, name: "vMGetKeyNum", sig: "VMUINT16 ()" },
    Field { off: 0x005c, name: "vMIsSupportTP", sig: "VMBOOLEAN ()" },
    Field { off: 0x0060, name: "CDownGetCompany", sig: "void (VMUINT8 *, VMUINT16)" },
    Field { off: 0x0064, name: "CDownGetServicePhone", sig: "void (VMUINT8 *, VMUINT16)" },
    Field { off: 0x0068, name: "vMIsSupportIdleMenu", sig: "VMBOOLEAN ()" },
    Field { off: 0x006c, name: "vMSendSms", sig: "VMBOOLEAN (VMUINT8 *, VMUINT8, VMUINT8 *, VMUINT16, VMBOOLEAN, SmSCallback)" },
    Field { off: 0x0070, name: "VmMakeCall", sig: "VMBOOLEAN (VMUINT8 *, VMUINT16)" },
    Field { off: 0x0074, name: "CDownGetData", sig: "VMUINT32 (" },
    Field { off: 0x0078, name: "GetCoolBarKernelCurrentVersion", sig: "VMUINT8 ()" },
    Field { off: 0x007c, name: "CoolBar_DownLoad_GetFile", sig: "VMBOOLEAN (VMUINT16 *, char *, DownLoadStateCallBackType)" },
    Field { off: 0x0080, name: "CoolBar_DownLoad_Stop", sig: "void ()" },
    Field { off: 0x0084, name: "vmDlGetCurrAppId", sig: "VMUINT16 ()" },
    Field { off: 0x0088, name: "vmSysIsVisibleApp", sig: "VMBOOLEAN (VMUINT16)" },
    Field { off: 0x008c, name: "cDownSetForceUpdate", sig: "void ()" },
    Field { off: 0x0090, name: "cDownGetModeAndVersion", sig: "void (VMUINT8 *, VMUINT16 *)" },
    Field { off: 0x0094, name: "mmiDynamicSetForceUpdate", sig: "void ()" },
    Field { off: 0x0098, name: "mmiDunamicGetModeAndVersion", sig: "void (VMUINT8 *, VMUINT16 *)" },
    Field { off: 0x009c, name: "vMSwitchLog", sig: "void (VMBOOLEAN)" },
    Field { off: 0x00a0, name: "Coolbar_GetResStatus", sig: "VMBOOLEAN (VMUINT16)" },
    Field { off: 0x00a4, name: "coolbar_Update_Tfold", sig: "VMBOOLEAN (VMUINT16 *)" },
    Field { off: 0x00a8, name: "CoolBar_EnterDmIn", sig: "void ()" },
    Field { off: 0x00ac, name: "vmInputText", sig: "VMBOOLEAN (CBInputTextCallback" },
    Field { off: 0x00b0, name: "vmInputPassword", sig: "VMBOOLEAN (CBInputTextCallback, CBInputTextParam *)" },
    Field { off: 0x00b4, name: "vmInputClose", sig: "void ()" },
    Field { off: 0x00b8, name: "vmInputIsOpen", sig: "VMBOOLEAN ()" },
    Field { off: 0x00bc, name: "VmRand", sig: "int ()" },
    Field { off: 0x00c0, name: "VmSrand", sig: "void (" },
    Field { off: 0x00c4, name: "VmGetSmsCenterNum", sig: "VMBOOLEAN (VMUINT8 *, VMUINT16)" },
    Field { off: 0x00c8, name: "VmGetPrjCustom", sig: "void (VMSTR, VMUINT32)" },
    Field { off: 0x00cc, name: "GetNetInfo", sig: "VMUINT8 (" },
    Field { off: 0x00d0, name: "VmGetCbNum", sig: "VMUINT16 ()" },
    Field { off: 0x00d4, name: "LzssEncode", sig: "void (VMUINT8 *, VMUINT32, VMUINT8 *" },
    Field { off: 0x00d8, name: "LzssDecode", sig: "void (VMUINT8 *, VMUINT32, VMUINT8 *, VMUINT32 *)" },
    Field { off: 0x00dc, name: "UpdateDmenu", sig: "void ()" },
    Field { off: 0x00e0, name: "UpdateCDownmenu", sig: "void ()" },
    Field { off: 0x00e4, name: "CbGetPlatfomName", sig: "VMCHAR *()" },
    Field { off: 0x00e8, name: "VmInnerAppInfo", sig: "VMBOOLEAN (" },
    Field { off: 0x00ec, name: "VmGetInnerAppIcon", sig: "VMBOOLEAN (VMUINT16, VMUINT8 *)" },
    Field { off: 0x00f0, name: "CDownGetAppType", sig: "VMUINT8 (VMUINT16)" },
    Field { off: 0x00f4, name: "vmSetGQQRunings", sig: "void (VMINT8)" },
    Field { off: 0x00f8, name: "vmGetGQQRunings", sig: "VMINT8 ()" },
    Field { off: 0x00fc, name: "vmGetQQAddress", sig: "void (VMUINT32 *, VMUINT32 *)" },
    Field { off: 0x0100, name: "VmGetScreenSize", sig: "VMUINT8 ()" },
    Field { off: 0x0104, name: "VmGetPlatformType", sig: "VMUINT8 ()" },
    Field { off: 0x0108, name: "VmDlGetIMEI", sig: "void (VMSTR, VMUINT32)" },
    Field { off: 0x010c, name: "VmGetIMSI", sig: "void (VMSTR, VMUINT32)" },
    Field { off: 0x0110, name: "VmGetLoginInfo", sig: "void (" },
    Field { off: 0x0114, name: "VmSetLoginInfo", sig: "void (LOGIN_INFO_T *)" },
    Field { off: 0x0118, name: "VmGetAppNameByIdFromList", sig: "VMBOOLEAN (VMUINT16, VMUINT16 *)" },
    Field { off: 0x011c, name: "VmUnInstallAppbyId", sig: "VMBOOLEAN (VMUINT16)" },
    Field { off: 0x0120, name: "VmGetDMenuFileName", sig: "void (VMUINT16 *)" },
    Field { off: 0x0124, name: "VmGetCDownFileName", sig: "void (VMUINT16 *)" },
    Field { off: 0x0128, name: "VmGetCDownAppUrl", sig: "void (char *, VMUINT8, VMUINT32)" },
    Field { off: 0x012c, name: "VmDlGetPreAppId", sig: "VMUINT16 ()" },
    Field { off: 0x0130, name: "VmParseMixDownData", sig: "VMBOOLEAN (VMUINT16 *, VMUINT16 *)" },
    Field { off: 0x0134, name: "CoolBar_DownLoad_CBE", sig: "VMBOOLEAN (VMUINT16 *, char *, VMUINT32, DownLoadStateCallBackType)" },
    Field { off: 0x0138, name: "Coolbar_PreLoadApp", sig: "VMUINT8 (VMUINT16)" },
    Field { off: 0x013c, name: "VmDlGetSpBf", sig: "VMUINT8 *()" },
    Field { off: 0x0140, name: "vMGetGameWinState", sig: "VMUINT8 ()" },
    Field { off: 0x0144, name: "VmGetHideText", sig: "VMCHAR *(VMCHAR *)" },
    Field { off: 0x0148, name: "VMPhbMultiSelectEntry", sig: "void (VMCHAR *, VMUINT16, VMUINT16, HandsetSelectCallback)" },
    Field { off: 0x014c, name: "VmSetCurActiveSim", sig: "void (VMUINT8)" },
    Field { off: 0x0150, name: "VmGetAllSimStatus", sig: "void (" },
    Field { off: 0x0154, name: "VmSendMMS", sig: "VMBOOLEAN (VMUINT8 *, VMUINT8, VMUINT8 *, VMUINT16, VMBOOLEAN)" },
    Field { off: 0x0158, name: "VmGetFoucsWin", sig: "VMUINT32 ()" },
    Field { off: 0x015c, name: "VmIsWinOpen", sig: "VMBOOLEAN (VMUINT32)" },
    Field { off: 0x0160, name: "VmIsInIdleWin", sig: "VMBOOLEAN ()" },
    Field { off: 0x0164, name: "VmIsInnerApp", sig: "VMBOOLEAN (VMUINT16)" },
    Field { off: 0x0168, name: "VmGetInnerAppVer", sig: "VMUINT16 (VMUINT16)" },
    Field { off: 0x016c, name: "VmGetMixMenuLength", sig: "VMUINT32 ()" },
    Field { off: 0x0170, name: "VmGetMixMenudata", sig: "VMUINT8 *()" },
    Field { off: 0x0174, name: "VmGetWpayCBMInfo", sig: "void (" },
    Field { off: 0x0178, name: "vMGetCurVerAllInfo", sig: "VMUINT8 *()" },
    Field { off: 0x017c, name: "VmSetFpsSleepFlag", sig: "void (VMBOOLEAN)" },
    Field { off: 0x0180, name: "vmSetSmsCenterNum", sig: "VMBOOLEAN (VMUINT8 *, VMUINT8)" },
    Field { off: 0x0184, name: "vmGetBuildTime", sig: "VMCHAR *()" },
    Field { off: 0x0188, name: "vmGetUsedTimes", sig: "VMUINT32 ()" },
    Field { off: 0x018c, name: "VmSysGetBatteryInfo", sig: "void (" },
    Field { off: 0x0190, name: "VmSysSetLcdBright", sig: "void (VMUINT8)" },
    Field { off: 0x0194, name: "VmSysResetLcdBright", sig: "void ()" },
    Field { off: 0x0198, name: "VmSysSetPowerSaveMode", sig: "void (VMBOOLEAN)" },
    Field { off: 0x019c, name: "VmGetOperatorMCC", sig: "VMUINT16 ()" },
    Field { off: 0x01a0, name: "VmGetOperatorMNC", sig: "VMUINT16 ()" },
    Field { off: 0x01a4, name: "VmGetSupportAppStore", sig: "VMBOOLEAN ()" },
    Field { off: 0x01a8, name: "cDownGetCompanyEx", sig: "void (VMUINT8, VMUINT8 *, VMUINT16)" },
    Field { off: 0x01ac, name: "VmSysGetCurrLcdLightInfo", sig: "void (" },
    Field { off: 0x01b0, name: "VmSysStartVibration", sig: "void (VMINT32)" },
    Field { off: 0x01b4, name: "VmSysStopVibration", sig: "void ()" },
    Field { off: 0x01b8, name: "VmSysOpenBrowser", sig: "void (VMUINT16 *)" },
    Field { off: 0x01bc, name: "VmSysSetSettingProfile", sig: "void (SETTING_PROFILE, VMUINT16 *, VMUINT16)" },
    Field { off: 0x01c0, name: "VmSysGetSettingProfile", sig: "void (SETTING_PROFILE, VMUINT16 *, VMUINT16)" },
    Field { off: 0x01c4, name: "VmSysGetSettingProfileName", sig: "void (SETTING_PROFILE, VMUINT16 *, VMUINT16)" },
    Field { off: 0x01c8, name: "VmSysSaveContactPerson", sig: "VMBOOLEAN (VMUINT16 *, VMUINT8, VMUINT8 *, VMUINT8, phb_phonebook_type_t)" },
];
static F_24: &[Field] = &[
    Field { off: 0x0000, name: "VMStartTimer", sig: "VMUINT16 (VMUINT32, TimerCBPtr, void *)" },
    Field { off: 0x0004, name: "VMStopTimer", sig: "void (VMUINT16)" },
    Field { off: 0x0008, name: "VMGetTickCount", sig: "VMUINT32 ()" },
    Field { off: 0x000c, name: "VMGetTotalSeconds", sig: "VMUINT32 ()" },
    Field { off: 0x0010, name: "VMGetCurrentTime", sig: "void (" },
    Field { off: 0x0014, name: "VMSysSleep", sig: "void (VMUINT32)" },
    Field { off: 0x0018, name: "VmSetSysTime", sig: "VMBOOLEAN (VMUINT8, VMUINT8, VMUINT8)" },
    Field { off: 0x001c, name: "VmSetSysDate", sig: "VMBOOLEAN (VMUINT16, VMUINT8, VMUINT8)" },
    Field { off: 0x0020, name: "VMIncreaseTime", sig: "void (VmDateTimeType *, VmDateTimeType *, VmDateTimeType *)" },
    Field { off: 0x0024, name: "VMDecreaseTime", sig: "void (VmDateTimeType *, VmDateTimeType *, VmDateTimeType *)" },
];
static F_25: &[Field] = &[
    Field { off: 0x0000, name: "VmutStrlenUcs2", sig: "VMUINT16 (const VMUINT16 *)" },
    Field { off: 0x0004, name: "VmutStrcpyUcs2", sig: "VMUINT16 *(VMUINT16 *, const VMUINT16 *)" },
    Field { off: 0x0008, name: "VmutStrcatUcs2", sig: "VMUINT16 *(VMUINT16 *, const VMUINT16 *)" },
    Field { off: 0x000c, name: "VmutExpandStrcpy", sig: "VMUINT16 *(VMUINT16 *, const char *)" },
    Field { off: 0x0010, name: "VmutStrncpyUcs2", sig: "VMUINT16 *(VMUINT16 *, const VMUINT16 *" },
    Field { off: 0x0014, name: "VmutExpandStrncpy", sig: "VMUINT16 *(VMUINT16 *, const char *, const VMUINT32)" },
    Field { off: 0x0018, name: "VmutExpandMemcpy", sig: "void *(void *" },
    Field { off: 0x001c, name: "VmutStrchrUcs2", sig: "VMUINT16 *(const VMUINT16 *, VMUINT16)" },
    Field { off: 0x0020, name: "VmutStrcmpUcs2", sig: "VMINT32 (const VMUINT16 *, const VMUINT16 *)" },
    Field { off: 0x0024, name: "VmutStricmpUcs2", sig: "VMINT32 (const VMUINT16 *, const VMUINT16 *)" },
    Field { off: 0x0028, name: "VmutStrncmpUcs2", sig: "VMINT32 (const VMUINT16 *, const VMUINT16 *, const VMUINT32)" },
];
static F_26: &[Field] = &[
    Field { off: 0x0000, name: "VmISPServiceOpen", sig: "void ()" },
    Field { off: 0x0004, name: "VmISPServiceClose", sig: "void ()" },
    Field { off: 0x0008, name: "VmDCVideoSetDisplayParam", sig: "VMUINT32 (" },
    Field { off: 0x000c, name: "VmDCDisplayAFrame", sig: "VMUINT32 (" },
    Field { off: 0x0010, name: "VmVideoIRAMMemInit", sig: "void (VMUINT32, void *)" },
    Field { off: 0x0014, name: "VmVideoIRAMMemMalloc", sig: "void *(VMUINT32, VMUINT32)" },
    Field { off: 0x0018, name: "VmVideoIRAMMemFree", sig: "void (VMUINT32, VMUINT32)" },
    Field { off: 0x001c, name: "VmVideoIRAMMemClose", sig: "void (VMUINT32, void *)" },
    Field { off: 0x0020, name: "VmCamOpenInit", sig: "VMBOOLEAN (void *)" },
    Field { off: 0x0024, name: "VmCloseCamera", sig: "VMBOOLEAN ()" },
    Field { off: 0x0028, name: "VmStartCaptureYUV", sig: "VMBOOLEAN (void *)" },
    Field { off: 0x002c, name: "VmStopCaptureYUV", sig: "VMBOOLEAN ()" },
    Field { off: 0x0030, name: "VmIsDoubleCamera", sig: "VMBOOLEAN ()" },
    Field { off: 0x0034, name: "VmSetCameraLoc", sig: "void (VMBOOLEAN)" },
    Field { off: 0x0038, name: "VmVideoDecInit", sig: "void *(unsigned int)" },
    Field { off: 0x003c, name: "VmVideoDecFrame", sig: "VMUINT32 (void *, const void *, VMUINT32, VMUINT32 *)" },
    Field { off: 0x0040, name: "VmVideoDecOutput", sig: "const void *(void *, void *, VMBOOLEAN)" },
    Field { off: 0x0044, name: "VmVideoDecOutputEx", sig: "const void *(void *, void *, void *, VMBOOLEAN)" },
    Field { off: 0x0048, name: "VmGetVideoDecParm", sig: "void (void *, VMUINT32 *, VMUINT32 *, VMUINT32 *)" },
    Field { off: 0x004c, name: "VmGetVideoDecParmEx", sig: "void (void *, VMUINT32 *, VMUINT32 *, VMUINT32 *)" },
    Field { off: 0x0050, name: "VmVideoDecClose", sig: "void (void *)" },
    Field { off: 0x0054, name: "VmVideoEncInit", sig: "void *(" },
    Field { off: 0x0058, name: "VmVideoEncFrame", sig: "VMUINT32 (void *, VMUINT8 *, VMUINT8 *, VMUINT32 *, VMUINT32 *)" },
    Field { off: 0x005c, name: "VmVideoEncClose", sig: "void (void *)" },
    Field { off: 0x0060, name: "VmGetVideoEncParm", sig: "void (VMUINT32, VMUINT32 *, VMUINT32 *)" },
    Field { off: 0x0064, name: "VmVideoPicScaling", sig: "void (VMUINT8 *, VMUINT8 *, VMUINT32, VMUINT32, VMUINT32, VMUINT32, VMUINT32)" },
    Field { off: 0x0068, name: "VmVideoPicUpturn", sig: "void (VMUINT8 *, VMUINT8 *, VMUINT32 *, VMUINT32 *)" },
    Field { off: 0x006c, name: "VmSetCamSampTime", sig: "void (VMUINT32)" },
    Field { off: 0x0070, name: "VmIsVideoPlayerRun", sig: "VMBOOLEAN ()" },
    Field { off: 0x0074, name: "VmPlayVideo", sig: "VMBOOLEAN (VMWCHAR *, void *)" },
    Field { off: 0x0078, name: "VmRegPlayVideoCb", sig: "void (playVideoCallBack)" },
    Field { off: 0x007c, name: "VmGetMediaFileInfo", sig: "VMBOOLEAN (VMWCHAR *" },
    Field { off: 0x0080, name: "VmPlayStreamingVideo", sig: "VMBOOLEAN (VMUINT16 *, VMUINT16, codec_SeekMode_e, codec_videoStreamingMode_e, codec_mediaFormat_t)" },
    Field { off: 0x0084, name: "VmStopStreamingVideo", sig: "VMBOOLEAN ()" },
    Field { off: 0x0088, name: "VmSetDownloadInterface", sig: "void (" },
    Field { off: 0x008c, name: "VmGetStreamingVideoHandle", sig: "VMUINT32 ()" },
    Field { off: 0x0090, name: "VmGetStreamingInfo", sig: "VMBOOLEAN (" },
    Field { off: 0x0094, name: "VmStreamingFileChange", sig: "VMBOOLEAN (" },
];

pub static MGR: &[Mgr] = &[
    Mgr { tag: "GameManagerOldTag", size: 636, fields: F_0 },
    Mgr { tag: "VmAudioManagerTag", size: 124, fields: F_1 },
    Mgr { tag: "VmBillingManagerTag", size: 176, fields: F_2 },
    Mgr { tag: "VmCtrlManagerTag", size: 84, fields: F_3 },
    Mgr { tag: "VmDFEnginelManagerTag", size: 60, fields: F_4 },
    Mgr { tag: "VmDFScriptManagerTag", size: 88, fields: F_5 },
    Mgr { tag: "VmDLWPayManagerTag", size: 36, fields: F_6 },
    Mgr { tag: "VmDlAppStoreManagerTag", size: 156, fields: F_7 },
    Mgr { tag: "VmDlImageManagerTag", size: 56, fields: F_8 },
    Mgr { tag: "VmDlLoadManagerTag", size: 44, fields: F_9 },
    Mgr { tag: "VmDlResourceManagerTag", size: 80, fields: F_10 },
    Mgr { tag: "VmGSensorManagerrTag", size: 48, fields: F_11 },
    Mgr { tag: "VmGameLcdManagerTag", size: 160, fields: F_12 },
    Mgr { tag: "VmGameUtilManagerTag", size: 160, fields: F_13 },
    Mgr { tag: "VmImManagerTag", size: 32, fields: F_14 },
    Mgr { tag: "VmIoManagerTag", size: 120, fields: F_15 },
    Mgr { tag: "VmLcdManagerTag", size: 380, fields: F_16 },
    Mgr { tag: "VmManagerTag", size: 212, fields: F_17 },
    Mgr { tag: "VmMemoryManagerTag", size: 108, fields: F_18 },
    Mgr { tag: "VmNetAppManagerTag", size: 244, fields: F_19 },
    Mgr { tag: "VmNetManagerTag", size: 172, fields: F_20 },
    Mgr { tag: "VmScreenManagerTag", size: 48, fields: F_21 },
    Mgr { tag: "VmStdManagerTag", size: 88, fields: F_22 },
    Mgr { tag: "VmSysManagerTag", size: 460, fields: F_23 },
    Mgr { tag: "VmTimeManagerTag", size: 40, fields: F_24 },
    Mgr { tag: "VmUcs2StrManagerTag", size: 44, fields: F_25 },
    Mgr { tag: "VmVideoManagerTag", size: 152, fields: F_26 },
];

pub fn mgr(tag: &str) -> Option<&'static Mgr> {
    MGR.iter().find(|m| m.tag == tag)
}

pub fn field(tag: &str, off: u32) -> Option<&'static Field> {
    let m = mgr(tag)?;
    m.fields
        .binary_search_by_key(&off, |f| f.off)
        .ok()
        .map(|i| &m.fields[i])
}
